import { renderToStaticMarkup } from 'react-dom/server'
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import App from '@/App'
import { ContainerScroll } from '@/components/ui/container-scroll-animation'

describe('ContainerScroll integration', () => {
  it('renders the supplied title and children from the shadcn ui component path', () => {
    const html = renderToStaticMarkup(
      <ContainerScroll
        titleComponent={<h1>Scroll Animations</h1>}
      >
        <img src="https://images.unsplash.com/photo-1462331940025-496dfbfc7564" alt="Galaxy preview" />
      </ContainerScroll>,
    )

    expect(html).toContain('Scroll Animations')
    expect(html).toContain('Galaxy preview')
    expect(html).toContain('h-[60rem] md:h-[80rem]')
    expect(html).toContain('border-4 border-[#6C6C6C]')
  })

  it('exposes the immersive intro on a hidden pre-landing route', () => {
    const html = renderToStaticMarkup(<App initialPath="/intro" />)

    expect(html).toContain('data-route="/intro"')
    expect(html).toContain('Follow the comet')
    expect(html).toContain('Enter Yuniverse')
    expect(html).toContain('href="/home"')
    expect(html).not.toContain('aria-label="Primary navigation"')
  })

  it('drives the comet into a shared final impact point with the planet', () => {
    const html = renderToStaticMarkup(<App initialPath="/intro" />)
    const css = readFileSync(new URL('../src/App.css', import.meta.url), 'utf8')
    const introSource = readFileSync(new URL('../src/pages/IntroPage.tsx', import.meta.url), 'utf8')

    expect(html).toContain('class="intro-comet-track"')
    expect(html).toContain('class="intro-comet-shell"')
    expect(html).toContain('class="intro-comet-fire"')
    expect(html).toContain('class="intro-comet-ring intro-comet-ring-1"')
    expect(html).toContain('class="intro-comet-ring intro-comet-ring-2"')
    expect(html).toContain('class="intro-comet-ring intro-comet-ring-3"')
    expect(html).toContain('class="intro-comet-compression"')
    expect(html).toContain('intro-sound-cloud')
    expect(html).toContain('class="intro-impact-planet"')
    expect(html).toContain('class="intro-planet-crack intro-planet-crack-a"')
    expect(html).toContain('class="intro-planet-piece intro-planet-piece-a"')
    const cometMarkup = html.slice(
      html.indexOf('class="intro-comet-track"'),
      html.indexOf('<div class="intro-progress"'),
    )
    expect(cometMarkup).not.toContain('intro-comet-final-gate')
    expect(css).toContain('--comet-start-x: 78vw')
    expect(css).toContain('--comet-end-x: 18vw')
    expect(css).toContain('--comet-path-angle: 38deg')
    expect(css).toContain('--comet-tail-angle: -52deg')
    expect(css).toContain('left: calc(100% - 8px)')
    expect(css).not.toContain('conic-gradient')
    expect(css).toContain('transform-origin: center center')
    expect(introSource).toContain("const impactPointX = '54vw'")
    expect(introSource).toContain("const impactPointY = '76vh'")
    expect(introSource).toContain("['78vw', impactPointX, impactPointX]")
    expect(introSource).toContain("['8vh', impactPointY, impactPointY]")
  })

  it('keeps work and life copy short in the immersive intro', () => {
    const html = renderToStaticMarkup(<App initialPath="/intro" />)

    expect(html).toContain('<h1>All AI</h1>')
    expect(html).not.toContain('<h1>Work</h1>')
    expect(html).toContain('<p>Projects, tools, and software craft.</p>')
    expect(html).toContain('<h1>razzle dazzle</h1>')
    expect(html).not.toContain('<h1>Life</h1>')
    expect(html).toContain('<p>Cities, school chapters, and small field notes.</p>')
    expect(html).toContain('<h1>all kinds of craps</h1>')
    expect(html).toContain('<h1>music, movie, picture</h1>')
    expect(html).not.toContain('Blog, collection, and the normal site are waiting past this gate.')
    expect(html).not.toContain('Software work, projects, and things still being organized.')
    expect(html).not.toContain('A public timeline across school, bachelor, and postgraduate chapters.')
  })

  it('uses non-repeated section titles and moves SNAP to the former BOOM side', () => {
    const html = renderToStaticMarkup(<App initialPath="/intro" />)
    const css = readFileSync(new URL('../src/App.css', import.meta.url), 'utf8')
    const blogMarkup = html.slice(
      html.indexOf('<p class="intro-label">Blog</p>'),
      html.indexOf('<p class="intro-label">Collection</p>'),
    )

    expect(html).toContain('<p class="intro-label">About</p><h1>黄新宇</h1>')
    expect(html).not.toContain('<span class="intro-title-line">About</span>')
    expect(css).toContain('font-size: 0.78rem')
    expect(blogMarkup).toContain('data-text="SNAP"')
    expect(blogMarkup).not.toContain('data-text="BOOM"')
    expect(css).toContain('.intro-sound-cloud-4')
    expect(css).toContain('right: 8%;')
    expect(css).not.toContain('.intro-sound-cloud-4 {\n  top: 26%;\n  left: 9%;')
  })

  it('keeps the collection title constrained inside the intro viewport', () => {
    const html = renderToStaticMarkup(<App initialPath="/intro" />)
    const css = readFileSync(new URL('../src/App.css', import.meta.url), 'utf8')

    expect(html).toContain('class="intro-copy intro-copy-right intro-copy-collection"')
    expect(css).toContain('.intro-copy-collection')
    expect(css).toContain('width: min(760px, 86vw)')
    expect(css).toContain('font-size: clamp(38px, 6.8vw, 76px)')
    expect(css).toContain('overflow-wrap: anywhere')
    expect(html).not.toContain('intro-sound-cloud-5')
  })

  it('renders sound effects as monochrome comic word-art bubbles', () => {
    const html = renderToStaticMarkup(<App initialPath="/intro" />)
    const css = readFileSync(new URL('../src/App.css', import.meta.url), 'utf8')

    expect(html).toContain('intro-sound-split-mask')
    expect(html).toContain('intro-sound-bubble')
    expect(html).toContain('intro-sound-word-outside')
    expect(html).toContain('intro-sound-word-inside')
    expect(html).toContain('class="intro-sound-halftone"')
    expect(html).toContain('intro-sound-style-burst')
    expect(html).not.toContain('intro-sound-slice')
    expect(html).toContain('intro-sound-style-stamp')
    expect(html).toContain('intro-sound-style-slash')
    expect(html).toContain('intro-sound-style-caption')
    expect(html).not.toContain('intro-sound-speed-lines')
    expect(css).toContain('clip-path: polygon')
    expect(css).toContain('radial-gradient(circle')
    expect(css).toContain('repeating-linear-gradient')
    expect(css).toContain('-webkit-text-stroke: 3px #000')
    expect(css).toContain('background: #fff')
    expect(css).toContain('filter: drop-shadow(0 0 0 #fff)')
    expect(css).toContain('0 0 0 8px #fff')
    expect(css).toContain('.intro-sound-style-burst::after')
    expect(css).toContain('transform: translate(-7px, 8px) skewX(-16deg)')
    expect(css).toContain('.intro-sound-style-burst .intro-sound-word-outside')
    expect(css).toContain('color: var(--comic-gray)')
    expect(css).not.toContain('.intro-sound-slice')
    expect(css).toContain('--comic-gray: #8f8f8f')
    expect(css).toContain('0 0 0 3px var(--comic-gray)')
    expect(css).toContain('text-shadow:')
    expect(css).toContain('var(--comic-gray)')
    expect(css).toContain('.intro-sound-word-outside')
    expect(css).toContain('.intro-sound-word-inside')
    expect(css).toContain('overflow: hidden')
    expect(css).toContain('color: #fff')
    expect(css).toContain('color: #000')
    expect(html).toContain('data-text="WHOOSH"')
    expect(html).toContain('data-text="SNAP"')
    expect(html).toContain('data-text="BOOM"')
    expect(css).not.toContain('.intro-sound-word::before')
    expect(css).toContain('paint-order: stroke fill')
    expect(css).not.toContain('.intro-sound-speed-lines')
  })

  it('progressively reveals a scroll-reactive monochrome cosmic background', () => {
    const html = renderToStaticMarkup(<App initialPath="/intro" />)
    const css = readFileSync(new URL('../src/App.css', import.meta.url), 'utf8')
    const introSource = readFileSync(new URL('../src/pages/IntroPage.tsx', import.meta.url), 'utf8')

    expect(html).toContain('class="intro-cosmos-layer intro-cosmos-near"')
    expect(html).toContain('class="intro-cosmos-opening-ui"')
    expect(html).toContain('class="intro-cosmos-opening-galaxy"')
    expect(html).toContain('class="intro-cosmos-opening-halftone"')
    expect(html).toContain('class="intro-cosmos-opening-orbit"')
    expect(html).toContain('class="intro-section-cosmos intro-section-cosmos-0 intro-section-cosmos-home-star"')
    expect(html).toContain('class="intro-section-cosmos intro-section-cosmos-1 intro-section-cosmos-planet"')
    expect(html).toContain('class="intro-section-cosmos intro-section-cosmos-2 intro-section-cosmos-signal"')
    expect(html).toContain('class="intro-section-cosmos intro-section-cosmos-3 intro-section-cosmos-star"')
    expect(html).toContain('class="intro-section-cosmos intro-section-cosmos-4 intro-section-cosmos-rays"')
    expect(html).toContain('class="intro-section-cosmos intro-section-cosmos-5 intro-section-cosmos-galaxy"')
    expect(html).toContain('class="intro-section-home-star"')
    expect(html).toContain('class="intro-section-planet"')
    expect(html).toContain('class="intro-section-signal-grid"')
    expect(html).toContain('class="intro-section-signal-core"')
    expect(html).toContain('class="intro-section-signal-node intro-section-signal-node-a"')
    expect(html).toContain('class="intro-section-star"')
    expect(html).toContain('class="intro-section-rays"')
    expect(html).toContain('class="intro-section-galaxy"')
    expect(html).toContain('class="intro-section-orbit"')
    expect(html).toContain('class="intro-section-dust"')
    expect(html).toContain('class="intro-cosmos-layer intro-cosmos-mid"')
    expect(html).toContain('class="intro-cosmos-layer intro-cosmos-deep"')
    expect(html).toContain('class="intro-cosmos-layer intro-cosmos-impact"')
    expect(html).toContain('class="intro-cosmos-galaxies"')
    expect(html).toContain('class="intro-cosmos-comic-stars"')
    expect(html).toContain('class="intro-cosmos-orbits"')
    expect(html).toContain('class="intro-cosmos-meteors"')
    expect(html).toContain('class="intro-cosmos-constellations"')
    expect(html).toContain('class="intro-cosmos-radials"')
    expect(css).toContain('.intro-cosmos-layer')
    expect(css).toContain('html:has(.intro-page)')
    expect(css).toContain('body:has(.intro-page)')
    expect(css).toContain('#root:has(.intro-page)')
    expect(css).toContain('.intro-cosmos-opening-ui')
    expect(css).toContain('top: -10%')
    expect(css).toContain('.intro-cosmos-opening-halftone')
    expect(css).toContain('border: clamp(6px')
    expect(css).toContain('.intro-section-cosmos')
    expect(css).toContain('.intro-section-cosmos-0')
    expect(css).toContain('.intro-section-cosmos-5')
    expect(css).toContain('.intro-section-cosmos-home-star')
    expect(css).toContain('.intro-section-cosmos-planet')
    expect(css).toContain('.intro-section-cosmos-signal')
    expect(css).toContain('.intro-section-cosmos-star')
    expect(css).toContain('.intro-section-cosmos-rays')
    expect(css).toContain('.intro-section-cosmos-galaxy')
    expect(css).toContain('.intro-section-home-star')
    expect(css).toContain('.intro-section-signal-grid')
    expect(css).toContain('.intro-section-signal-core')
    expect(css).toContain('.intro-section-signal-node')
    expect(css).toContain('.intro-section-star')
    expect(css).toContain('animation: introSectionCosmosFloat')
    expect(css).toContain('@keyframes introSectionCosmosFloat')
    expect(css).toContain('z-index: 0')
    expect(css).toContain('z-index: 6')
    expect(css).toContain('z-index: 5')
    expect(css).toContain('.intro-cosmos-mid')
    expect(css).toContain('.intro-cosmos-deep')
    expect(css).toContain('.intro-cosmos-impact')
    expect(css).toContain('animation: introCosmicDrift')
    expect(css).toContain('@keyframes introCosmicDrift')
    expect(css).toContain('mask-image: radial-gradient')
    expect(css).toContain('repeating-radial-gradient')
    expect(css).toContain('background-size: 18px 18px')
    expect(introSource).toContain('const openingCosmosOpacity = useTransform(scrollYProgress')
    expect(introSource).toContain('const openingCosmosY = useTransform(scrollYProgress')
    expect(introSource).toContain('const nearCosmosOpacity = useTransform(scrollYProgress')
    expect(introSource).toContain('const midCosmosOpacity = useTransform(scrollYProgress')
    expect(introSource).toContain('const deepCosmosOpacity = useTransform(scrollYProgress')
    expect(introSource).toContain('const impactCosmosOpacity = useTransform(scrollYProgress')
    expect(introSource).toContain("cosmosType: 'home-star'")
    expect(introSource).toContain("cosmosType: 'planet'")
    expect(introSource).toContain("cosmosType: 'signal'")
    expect(introSource).toContain("cosmosType: 'star'")
    expect(introSource).toContain("cosmosType: 'rays'")
    expect(introSource).toContain("cosmosType: 'galaxy'")
    expect(introSource).toContain('renderSectionCosmos(chapter.cosmosType)')
    expect(introSource).toContain('style={{ opacity: midCosmosOpacity, x: midCosmosX, y: midCosmosY }}')
    expect(introSource).toContain('style={{ opacity: deepCosmosOpacity, x: deepCosmosX, y: deepCosmosY, scale: deepCosmosScale }}')
  })

  it('stages the explosion from zero and morphs the comet into FINAL GATE', () => {
    const html = renderToStaticMarkup(<App initialPath="/intro" />)
    const css = readFileSync(new URL('../src/App.css', import.meta.url), 'utf8')
    const introSource = readFileSync(new URL('../src/pages/IntroPage.tsx', import.meta.url), 'utf8')

    expect(html).toContain('class="intro-scroll-cosmos"')
    expect(html).toContain('class="intro-scroll-starfield"')
    expect(html).toContain('class="intro-scroll-dust"')
    expect(html).toContain('class="intro-scroll-rays"')
    expect(html).toContain('class="intro-scroll-meter"')
    expect(html).toContain('class="intro-collision-stage"')
    expect(html).toContain('class="intro-impact-flash"')
    expect(html).toContain('class="intro-impact-burst"')
    expect(html).toContain('class="intro-impact-radials"')
    expect(html).toContain('class="intro-impact-shockwave intro-impact-shockwave-a"')
    expect(html).toContain('class="intro-impact-smoke intro-impact-smoke-a"')
    expect(html).toContain('class="intro-impact-debris intro-impact-debris-a"')
    expect(html).toContain('class="intro-sound intro-impact-boom"')
    expect(html).toContain('class="intro-sound-split-mask intro-sound-style-burst intro-impact-boom-word"')
    expect(html).toContain('data-text="BOOM"')
    expect(html).toContain('style="opacity:0;transform:scale(0.2)"')
    expect(html).toContain('<section class="intro-gate" aria-label="Yuniverse entry">')
    expect(html).toContain('class="intro-comet-final-gate"')
    expect(html).toContain('<p class="intro-label">Final gate</p>')
    expect(html).toContain('<a href="/home" class="intro-enter">Enter Yuniverse</a>')
    expect(html).not.toContain('intro-comet-final-title')
    expect(html).not.toContain('class="intro-gate-panel"')
    expect(html).not.toContain('<h2 id="intro-gate-title">Enter Yuniverse</h2>')
    expect(css).toContain('.intro-scroll-cosmos')
    expect(css).toContain('.intro-collision-stage')
    expect(css).toContain('.intro-impact-flash')
    expect(css).toContain('.intro-impact-burst')
    expect(css).toContain('.intro-impact-radials')
    expect(css).toContain('.intro-impact-shockwave')
    expect(css).toContain('.intro-impact-boom')
    expect(css).toContain('.intro-comet-final-gate')
    expect(css).toContain('background: #000')
    expect(css).toContain('radial-gradient(circle at 2px 2px')
    expect(css).toContain('background-size: 10px 10px')
    expect(css).toContain('clip-path: polygon')
    expect(css).toContain('mix-blend-mode: screen')
    expect(css).toContain('box-shadow: 8px 8px 0 #3f3f3f')
    expect(css).toContain('pointer-events: auto')
    expect(css).toContain('rotate: 0deg')
    expect(css).not.toContain('.intro-gate-panel')
    expect(introSource).toContain('const flashOpacity = useTransform(scrollYProgress')
    expect(introSource).toContain('const burstScale = useTransform(scrollYProgress')
    expect(introSource).toContain('const impactBoomOpacity = useTransform(scrollYProgress')
    expect(introSource).toContain('const shockwaveScale = useTransform(scrollYProgress')
    expect(introSource).toContain('const finalGateOpacity = useTransform(scrollYProgress')
    expect(introSource).not.toContain('const cometGateOpacity = useTransform(scrollYProgress')
    expect(introSource).not.toContain('className="intro-gate-panel"')
    expect(css).not.toContain('nebula')
    expect(css).not.toContain('colorful')
  })
})
