import type { BlogPost } from '../../data/types'

export const agentDataFlywheelObservabilitySeo = {
  slug: 'agent-data-flywheel-observability-seo',
  title: 'Agent 开发里的数据飞轮：从可观测性到 SEO',
  date: '2026-05-22',
  excerpt:
    '整理我对 Agent 数据飞轮的理解：先用可观测性记录真实使用，再用 eval 和归因推动系统改进，同时通过 blog 和评论区承接 SEO 流量，让更多真实需求反哺平台。',
  content: [
    '最近在做 Agent Infrastructure 时，我越来越感觉到，Agent 产品和传统软件很不一样的一点在于：它不是上线之后就稳定运行，而是上线之后才真正开始学习真实世界。',
    '一个 Agent 在 demo 阶段看起来能工作，通常只能说明它在少量理想样本上跑通了。但真实用户会用各种意想不到的方式提问，会中断任务，会重复表达，会对答案不满意但不一定点差评，也会在某些场景里把 Agent 当成搜索、助手、客服、运营顾问甚至半个同事来用。',
    '所以 Agent 的长期能力，不只取决于初始 prompt、模型选择或工具设计，而取决于系统能不能持续把真实使用中的信号收集回来，再转化成下一轮产品、模型、知识库和体验优化。这就是我理解的 Agent 数据飞轮。',
    '## 可观测性是数据飞轮的起点',
    '我之前在实习记录里写过一部分 Agent Infrastructure 的工作：把模型调用、工具调用、MCP 入参、span 耗时、token 消耗等信息通过 OpenTelemetry 接入后端，再按用户和 conversation_id 做分析。',
    '当时做这些东西，第一层目标其实很朴素：看清楚一次对话里到底发生了什么。',
    '比如一次任务为什么慢，是模型本身慢，还是某个工具调用慢？token 为什么突然变多，是 leader agent 拿了太多不相关上下文，还是某个 MCP 返回了过长结果？用户体验不好，是模型没理解任务，还是工具路由错了，还是业务数据本身没有查到？',
    '这些问题如果没有 trace，就很容易变成凭感觉调 prompt。看起来是在优化 Agent，实际是在猜。',
    '但有了可观测性之后，Agent 的每次运行就不再只是一次黑盒调用，而是一条可以分析的轨迹：用户输入是什么，模型如何规划，调用了哪些工具，每个工具返回了什么，哪里耗时最高，哪里消耗 token 最多，最后用户有没有继续追问或放弃。',
    '这些 trace 本身就是数据飞轮的原材料。',
    '## 数据飞轮不是简单堆数据',
    '我现在对数据飞轮的理解，不是“多收集用户数据，然后拿去训练模型”这么简单。',
    '更准确地说，它应该是一条闭环：',
    '```text\n用户使用 Agent\n -> 系统记录 trace、反馈、行为信号和业务结果\n -> 从中识别失败模式和高价值样本\n -> 归因到 prompt、RAG、tool、router、模型或产品体验问题\n -> 做对应改进\n -> 通过 eval 和灰度验证\n -> 推回线上\n -> 产生更多真实使用数据\n```',
    '这里最关键的一步是归因。',
    '同样是用户不满意，原因可能完全不同。如果是检索失败，那应该改知识库、embedding、query rewrite 或数据同步；如果是模型拿到了正确上下文但回答不好，那可能要改 prompt、few-shot 或 fine-tune；如果是 multi-agent 系统里分配错了 specialist agent，那问题在 router；如果是工具返回的数据不完整，那应该修后端接口或业务数据链路。',
    '所以数据飞轮的核心不是收集更多失败样本，而是把失败样本变成可解释、可分类、可复现、可修复的工程对象。',
    '## 从 trace 到 eval',
    '可观测性解决的是“看见发生了什么”，但数据飞轮还需要解决“怎么判断有没有变好”。',
    '这就需要 eval。',
    '一个比较健康的流程是：从线上 trace 里挑出典型失败 case，整理成 regression eval。以后每次改 prompt、换模型、调整工具、优化 router，都要先跑这些 eval，确保新的版本没有把老问题重新引入。',
    '对 Agent 来说，eval 不能只看最终答案。很多时候最终答案错，是因为中间某一步已经错了。比如工具选错、参数传错、上下文漏掉、过早结束任务、没有追问必要信息。这些都应该从 trace 里抽出来，变成更细粒度的评估指标。',
    '也就是说，trace 是问题现场，eval 是把问题现场沉淀成回归测试。',
    '## SEO 也是数据飞轮的一部分',
    '如果只从模型工程角度看，数据飞轮通常停留在“用户使用产品 -> 反馈 -> 改进模型”。但对一个软件平台来说，流量本身也应该进入飞轮。',
    '比如我们的网站、博客、文档、案例页和评论区，实际上都可以承担 SEO 入口的角色。用户可能不是直接搜索产品名，而是搜索一些更具体的问题：',
    '```text\nAI agent observability 怎么做\nagent trace token cost 分析\nLLM agent 数据飞轮\nagent eval 怎么设计\nMCP 工具调用日志\nAI agent SEO 自动化\n本地生活商户 AI 运营助手\n```',
    '如果 blog 里自然覆盖这些关键词，评论区又持续出现真实用户的问题、补充场景和长尾表达，搜索引擎就更容易理解这个网站和哪些主题相关。被搜索到的概率提高，带来的访问量增加，访问量又会转化成更多试用、更多对话、更多反馈和更多真实业务场景。',
    '这时 SEO 就不只是获客手段，而是数据飞轮的入口层。',
    '```text\nBlog / 文档 / 评论区覆盖关键词\n -> 搜索流量增加\n -> 更多用户进入产品\n -> 更多 Agent 使用数据和反馈\n -> 反哺平台能力、内容选题和产品体验\n -> 产生更好的案例、文档和博客\n -> 继续提升搜索覆盖\n```',
    '这里有一个边界：SEO 不能变成关键词堆砌。更有效的方式应该是把关键词放进真实问题里。标题、摘要、H2、FAQ、案例描述、评论引导都可以围绕用户真的会搜索的问题展开，而不是机械重复“AI Agent 数据飞轮”这几个词。',
    '评论区尤其适合做长尾关键词沉淀。因为真实用户的表达往往比我们自己写的 marketing copy 更接近搜索词。一个用户可能不会搜索“生产级智能体反馈闭环架构”，但会搜索“agent 回答错了怎么收集反馈”“怎么知道 agent 调了哪个工具”“怎么统计 LLM token 成本”。这些自然语言问题，反而是更有价值的 SEO 入口。',
    '## 软件平台如何吃到这部分数据',
    'SEO 带来的不只是流量，还会带来更丰富的用户意图。',
    '用户从不同关键词进入平台，说明他们关心的问题不同。有的人关心 observability，有的人关心成本，有的人关心 eval，有的人关心商户运营，有的人关心自动发评论、自动写内容、自动分析店铺数据。',
    '这些入口信息可以反哺产品：',
    '- 哪些关键词带来高转化，说明哪些问题更痛。\n- 哪些文章带来注册但不活跃，说明产品承接可能不够清楚。\n- 哪些评论问题反复出现，说明需要补功能、补文档或补模板。\n- 哪些使用路径 token 消耗高但结果差，说明需要优化 agent routing 或工具调用。\n- 哪些用户输入频繁失败，可以进入 eval dataset 或 prompt 改进样本。',
    '这样一来，SEO、内容、评论、产品使用、trace、eval、模型优化就不是分散的增长动作，而是同一个系统里的不同数据层。',
    '## 我现在对 Agent 数据飞轮的理解',
    '如果把这件事压缩成一句话：',
    'Agent 数据飞轮不是让模型自动变聪明，而是让系统持续知道用户从哪里来、想完成什么、Agent 在哪里失败、应该由哪一层来修，以及修完之后有没有真的变好。',
    '可观测性让我们看见 Agent 的执行过程。Eval 让我们判断改动有没有收益。SEO 和评论让更多真实需求进入系统。产品数据和用户反馈让平台知道下一步该优化什么。',
    '这几个部分接起来之后，Agent 才不是一个静态功能，而是一个会随着真实使用不断变厚的系统。',
    '## 参考阅读',
    '- [AI Agent Data Flywheels: Closing the Loop Between Production Deployments and Model Improvement](https://zylos.ai/research/2026-04-16-ai-agent-data-flywheels-production-feedback-loops)\n- [Self-Evolving Agents - A Cookbook for Autonomous Agent Retraining](https://developers.openai.com/cookbook/examples/partners/self_evolving_agents/autonomous_agent_retraining)',
  ],
  aiDisclosure: '本文由 AI 协助整理表达，内容来自个人实习记录和对 Agent 数据飞轮的技术思考。',
  readingMinutes: 5,
  category: 'software',
  tags: ['Agent', '数据飞轮', '可观测性', 'SEO', 'LLMOps'],
  status: 'published',
} satisfies BlogPost
