import type { BlogPost } from '../../data/types'

export const codexLegendaryDriverContextNoise = {
  slug: 'codex-legendary-driver-context-noise',
  title: 'Codex 传奇驾驶员 02：减少噪音，别把上下文当垃圾桶',
  date: '2026-06-11',
  excerpt:
    '上下文不是越多越好。真正稳定的 agent 工作流，应该区分本地状态和模型可见上下文，动态选择工具，主动压缩长会话，并把 memory 做成按需检索。',
  content: [
    '用 Codex 和各种 agent 工具久了以后，我越来越觉得，一个很重要的能力不是“给模型更多信息”，而是“知道哪些信息不该给模型”。',
    '很多人一开始会本能地把所有东西都塞进上下文：项目背景、文件内容、历史对话、工具列表、长期记忆、搜索结果、日志、报错、猜测、总结。看起来很充分，实际上很容易把模型淹没。',
    '上下文不是垃圾桶。',
    '对 agent 来说，噪音有几种典型来源：不相关的历史消息、过多的工具定义、已经处理过的 tool result、过期的中间结论、全局注入的 memory、太厚的 system prompt，以及一个任务里其实用不到的流程约束。',
    '所以我现在更倾向于把“减少噪音”当成 agent 使用和 agent 工程里的基本功。',
    '## 先拆上下文类型',
    'OpenAI Agents SDK 的 context management 文档里有一个很清楚的区分：一种 context 是本地代码可见的 context，另一种是 LLM 可见的 context。',
    '这个区分非常重要。',
    '本地 context 可以放用户状态、依赖、logger、数据 fetcher、helper function，工具执行时可以读它，但它不会自动进入模型看到的 prompt。真正需要模型判断的信息，才应该进入 conversation history、instructions、input、retrieval 或 tool result。',
    '这给我的启发是：不要把所有状态都翻译成人话塞给模型。',
    '很多东西只需要系统知道，不需要模型知道。比如 user id、内部对象、完整配置、工具运行时状态、缓存、数据库连接、原始日志文件路径，这些更适合留在本地状态里。模型只需要看到它完成判断所需的那一小部分。',
    '这也是减少噪音的第一步：先问清楚，这个信息是给系统用的，还是给模型判断用的？',
    '## 工具不要全量暴露',
    '第二个很大的噪音来源是工具。',
    '工具越多，模型看起来越强，但 tool definitions 本身也会吃上下文。Anthropic 在 manage tool context 文档里把 tool context bloat 单独拿出来讲，建议用 tool search、programmatic tool calling、prompt caching、context editing 这些方式来减少工具带来的上下文负担。',
    '这里有一个很直观的数据：Anthropic 的 tool search 文档提到，一个包含 GitHub、Slack、Sentry、Grafana、Splunk 这类多服务器工具的典型设置，工具定义本身可能到 55k tokens 左右；而 tool search 通常可以减少 85% 以上的上下文占用，因为模型一开始只看到搜索工具，真正需要时再加载 3 到 5 个相关工具。',
    '这和我使用 Codex 的感受很一致。',
    '工具不要一股脑全开。工具太多以后，模型不只是 context 变长，还会开始纠结该用哪个工具。很多工具描述又长又重，功能还互相重叠，模型选错工具的概率也会变高。',
    '更好的方式是按任务动态暴露工具。写代码时给代码相关工具；查资料时给搜索和文档工具；做 UI 验证时给浏览器；需要提交时再给 git 流程。不要让一个小任务一上来就背着所有工具定义出发。',
    '## 长会话不能 append-only',
    '第三个问题是长会话。',
    '很多人用 agent 时，会默认把对话一直 append 下去。前面所有讨论、所有工具结果、所有失败尝试、所有中间输出都留着。短期看方便，长期看就是噪音越来越多。',
    'Anthropic 的 compaction 思路是，在上下文接近阈值时生成摘要，让后续请求从摘要继续，而不是继续背着所有旧消息。context editing 则更进一步，可以清理旧 tool result，甚至管理 thinking blocks。',
    '这背后的原则很简单：长任务需要连续性，但不需要保留所有原始过程。',
    '比如一个 bug 已经定位完，早期的十几轮搜索结果就不一定还要原样留在上下文里。更重要的是留下：现象是什么、确认过哪些路径、排除了什么、根因是什么、下一步要验证什么。',
    '同样，做一个前端页面时，早期的设计探索、失败截图、临时方案，也不一定需要永远留着。到实现阶段，模型需要的是当前决策、最终设计约束、待办事项和验收标准。',
    '所以我现在会更主动地让 Codex 做阶段性收束：把已经完成的部分总结成短状态，把无用过程从工作记忆里拿掉。不要让一个任务因为历史太长，最后变成模型在旧信息里翻垃圾。',
    '## 按任务路由，而不是一个大 prompt 管全部',
    '还有一种噪音来自“万能大 prompt”。',
    '有些人会写一个巨大的 system prompt，希望它同时负责需求分析、架构设计、代码实现、测试、代码 review、文档、提交、部署、沟通风格、异常处理。看起来很完整，但实际很容易变重。',
    'Anthropic 的 Building Effective Agents 里有一个我很认同的建议：先用最简单的方案，只有在确实需要时再增加复杂度。能用单次 LLM 调用加检索解决，就不要硬上 agent；能用 routing、prompt chaining 解决，就不要让一个开放式 agent 管所有事情。',
    '对 Codex 使用也是一样。',
    '不是每个任务都需要完整流程。改一个 typo，不需要进入复杂 planning；写一个小测试，不一定需要长篇架构分析；查一个函数引用，也不用加载所有 repo 规则。',
    '更好的方式是按任务路由：需求没想清楚时用 brainstorming；需要被追问时用 grill-me；长任务才用 planning-with-files；写博客走博客流程；提交代码走提交流程。',
    '这样每个流程都更轻，也更容易调试。模型看到的上下文少了，行为反而更稳定。',
    '## Memory 应该是检索结果，不是背景墙',
    '最后一个噪音来源是 memory。',
    '长期记忆很有价值，但我不喜欢把 memory 做成全局背景墙。所谓背景墙，就是不管任务是什么，都把一堆用户偏好、项目历史、过往结论、个人信息全部塞进 prompt。',
    '这很危险，也很吵。',
    'LangChain 的 context engineering 总结了四个动作：write、select、compress、isolate。也就是可以写入长期记忆，但每一步要选择相关记忆；可以压缩上下文；也可以用 state、sub-agent、sandbox 等方式隔离重对象。',
    '我觉得最关键的是 select。',
    'Memory 不是“越多越智能”，而是“需要时能找回来”。比如我之前写过某个项目的架构笔记，那它不应该每次都出现。只有当我正在改这个项目、并且这个模块相关时，它才应该被检索出来。否则 memory 也会变成噪音。',
    '好的 memory 系统应该像搜索结果，而不是 system prompt。它应该被选择、排序、压缩，然后以合适的粒度进入当前任务。',
    '## 我的使用原则',
    '把这些主流做法放到一起，我现在会用几个很简单的原则来约束自己：',
    '第一，能留在本地状态里的东西，不要塞进 prompt。',
    '第二，工具按需暴露，不要让模型一开始背着所有工具定义。',
    '第三，长任务要阶段性总结，不要 append-only。',
    '第四，能用 routing 和 prompt chaining 的任务，不要强行变成一个大 agent。',
    '第五，memory 要检索，不要全局注入。',
    '第六，用 tracing、测试和实际效果看上下文工程有没有帮助，不要只凭感觉优化。',
    '这些原则说到底都是同一件事：让模型只看它此刻真正需要看的东西。',
    '## 结尾',
    '以前我会觉得，上下文越多，模型越不容易漏东西。现在我反而觉得，上下文越干净，模型越容易做对事情。',
    'Codex 也是一样。',
    '很多时候，驾驶员的价值不在于不断给 Codex 加东西，而在于帮它减东西：减掉无关文件，减掉无关工具，减掉过期历史，减掉太重的流程，减掉不该进入 prompt 的 memory。',
    '减少噪音，不是为了省 token 而已。它是在保护模型的注意力。',
    '这也是我理解的 context engineering：不是把上下文窗口填满，而是把正确的信息放到正确的位置。',
    '## 参考资料',
    '- OpenAI Agents SDK Context Management：https://openai.github.io/openai-agents-python/context/\n- Anthropic Manage Tool Context：https://platform.claude.com/docs/en/agents-and-tools/tool-use/manage-tool-context\n- Anthropic Tool Search Tool：https://platform.claude.com/docs/en/agents-and-tools/tool-use/tool-search-tool\n- Anthropic Compaction：https://platform.claude.com/docs/en/build-with-claude/compaction\n- Anthropic Context Editing：https://platform.claude.com/docs/en/build-with-claude/context-editing\n- Anthropic Building Effective Agents：https://www.anthropic.com/engineering/building-effective-agents\n- LangChain Context Engineering for Agents：https://www.langchain.com/blog/context-engineering-for-agents',
  ],
  aiDisclosure:
    '本文由 AI 协助整理表达，内容来自个人使用 Codex 和阅读主流 agent 工程资料后的总结。',
  readingMinutes: 6,
  category: 'software',
  topic: 'ai-tools',
  series: 'codex-legendary-driver',
  tags: ['Codex', 'Context Engineering', 'Agent', 'AI Coding'],
  status: 'published',
} satisfies BlogPost
