import type { BlogPost } from '../../data/types'

export const codexLegendaryDriverLoopEngineering = {
  slug: 'codex-legendary-driver-loop-engineering',
  title: 'Codex 传奇驾驶员 03：Loop Engineering，让 Agent 在无人盯守时工作',
  date: '2026-06-17',
  excerpt:
    'AI 的时间不是人的时间。Loop Engineering 的核心不是写更聪明的 prompt，而是设计交付条件、外部状态和停止机制，让 Codex 在没人盯着的时候也能持续推进。',
  content: [
    'AI 的时间不是人的时间。',
    '一个 agent 在后台多跑十分钟，消耗的是 token 和算力；一个人盯着它跑十分钟，消耗的是注意力、上下文和判断力。',
    '所以使用 Codex 时，最值钱的能力不是每一轮都写出更聪明的 prompt，而是让它在没人盯着的时候也能工作。',
    'Loop Engineering 讲的就是这件事：设计一个循环，让 agent 根据清楚的交付条件持续推进、检查、纠偏，并在真正需要人的地方停下来。',
    'Prompt 解决的是这一轮怎么说。Loop 解决的是人不在场时，它怎么继续做。',
    '## 人盯着 Agent，是最贵的用法',
    '很多人使用 coding agent 的方式还是同步聊天模式。',
    '提出需求，等待输出，发现问题，补一句 prompt，再等它修改。它问一个问题，人答一个问题。它跑一步，人看一步。它卡住了，人再推一下。',
    '这个模式的问题不是不能工作，而是太占人。',
    '如果 agent 每推进一小步都需要人确认，那它并没有真正释放人的时间。人还是被锁在同一个任务里，只是从“亲自写代码”变成了“亲自盯着别人写代码”。',
    '这会吃掉 agent 最有价值的异步优势。',
    'AI 可以慢一点，可以多试几次，可以在后台跑。人不应该陪着它慢，不应该陪着它试，不应该一直停留在同一个上下文里等它下一句话。',
    '真正值钱的工作方式是：人把目标、边界和交付条件定义清楚，然后离开。Agent 自己推进，自己检查，自己修正，最后交付一个可以验收的结果。',
    '## Loop Engineering 的核心是交付条件',
    'Loop Engineering 不是让 agent 无限自动运行。',
    '它的核心是交付条件。',
    '你不能只告诉 Codex：“继续做完。”你要告诉它什么叫做“做完”。',
    '比如：',
    '- 哪些文件可以改，哪些不能改。\n- 应该遵守什么现有模式。\n- 必须跑哪些测试或检查。\n- 如果测试失败，允许自己修几轮。\n- 如果发现需求不清，应该停下来问人。\n- 如果涉及权限、数据结构、计费、删除、线上配置，必须停下来。\n- 最后交付时要给出 diff 摘要、验证结果和剩余风险。',
    '这些条件越清楚，人越不需要盯过程。',
    '差的 loop 会不断把问题抛回给人。好的 loop 会自己处理低风险推进，只在高价值判断点让人回来。',
    '所以 loop engineering 的重点不是“让 AI 自主”，而是定义 AI 在什么范围内可以自主。',
    '## HITL 不是越多越安全',
    'Human-in-the-loop 很重要，但它不是越多越好。',
    '很多时候，HITL 被误用成了每一步都让人确认。看起来安全，实际是在把 agent 的效率打掉。',
    '如果每次读文件要问人，每次改代码要问人，每次跑测试要问人，每次遇到小错误要问人，那人就重新变成了系统的瓶颈。',
    '更合理的方式是把 HITL 放在真正需要人的地方：',
    '- 目标不清楚。\n- 存在多个产品或架构方向。\n- 要改高风险模块。\n- 要做不可逆操作。\n- 测试无法覆盖核心风险。\n- Agent 连续尝试后没有新信息。\n- 最终结果需要合并、发布或对外承诺。',
    '人应该处理判断、风险和验收，不应该处理普通推进。',
    'Loop engineering 的目标不是移除人，而是减少低价值 HITL。',
    '## Ralph Loop 把状态放在 Agent 外面',
    'Ralph 是一个很直接的 autonomous AI agent loop。',
    '它反复启动 AI coding tool，直到 `prd.json` 里的所有 PRD item 都完成。每一次迭代都是新的 agent context，不依赖上一轮聊天历史。跨轮记忆放在外部：`git history`、`progress.txt`、`prd.json`。',
    '这点很重要。',
    '如果一个 loop 的状态只存在于聊天记录里，它就很难真正无人盯守。上下文会变长，会污染，会丢重点，也会让人越来越难判断 agent 现在到底做到哪里。',
    'Ralph 的结构把这件事拆开了：',
    '- `prd.json` 记录任务列表和完成状态。\n- `passes: false` 表示还没完成。\n- 每轮选择最高优先级的未完成 story。\n- 每轮只实现一个 story。\n- typecheck 和 tests 是质量检查。\n- 检查通过后才 commit。\n- 完成后把 story 标成 `passes: true`。\n- `progress.txt` 记录 learnings，给下一轮读取。\n- 所有 story 都通过后输出 `COMPLETE`，loop 停止。',
    '它的价值不在于 shell loop 本身，而在于把目标、状态、验证、记忆和停止条件都外部化了。',
    '这就是 loop engineering 最关键的一点：不要把人的注意力当状态存储，也不要把聊天记录当长期记忆。',
    '状态应该在文件里。',
    '验收应该在检查里。',
    '停止条件应该在协议里。',
    '## Goal Mode 是同一个方向',
    'Codex 的 Goal mode 也在往同一个方向走。',
    '一个 goal 不只是“开始做这件事”的 prompt，它也是 Codex 判断自己有没有完成的 completion criteria。',
    '这和 Ralph 的 `prd.json`、`passes`、checks、`COMPLETE` 是同一类思想：agent 需要的不只是任务描述，还需要完成标准。',
    '不要只写“帮我完成迁移”，而要写清楚迁移完成后应该满足什么状态。',
    '不要只写“优化性能”，而要写清楚指标要到哪里。',
    '不要只写“修 bug”，而要写清楚复现方式、验证方式和不能破坏的行为。',
    'Goal 是 loop 的锚点。',
    '如果 goal 写得模糊，agent 就只能不断猜。',
    '如果 goal 写得可检查，agent 才能在没人盯着的时候持续靠近完成状态。',
    '## 从监督者变成验收者',
    '手动 prompt 模式里，人是监督者。',
    '人要盯着 agent 有没有跑偏，要提醒它别改错文件，要告诉它继续，要检查它有没有忘记测试。',
    'Loop 模式里，人更像验收者。',
    '人在开始前定义交付条件，在结束后验收结果。中间过程尽量让 agent 自己消化。',
    '这要求驾驶员提前设计好几个东西：',
    '- 上下文：项目结构、代码风格、约束和禁区。\n- 状态：当前做到哪里，排除了什么，下一步是什么。\n- 检查：每轮推进后如何验证。\n- 纠偏：验证失败时允许怎么修。\n- 停止条件：什么时候不能继续猜。\n- 交付格式：最后怎么让人快速判断结果。',
    '没有这些东西，agent 只能靠聊天继续。',
    '有了这些东西，agent 才能在没人盯着的时候工作。',
    '## Codex 的组件都在服务 Loop',
    'Codex 里的很多能力，都可以放到 loop engineering 这个框架里理解。',
    'Skill 负责沉淀流程。把重复出现的要求写成 `SKILL.md`，让 Codex 下次不用从零理解你的工作方式。',
    'Worktree 负责隔离尝试。Agent 可以在独立环境里推进，不会直接污染主工作区。',
    'Automation 负责启动循环。一些任务不应该等人想起来才开始，比如巡检、整理、检查、定期更新。',
    'Connector 负责接入外部状态。真实工作不只在代码仓库里，还在 issue、文档、设计稿、日志和部署系统里。',
    'Subagent 负责拆分角色。探索、实现、审查、总结可以拆给不同 agent，避免所有任务都塞进同一个上下文。',
    '这些组件单独看只是功能。组合起来，它们就是让 Codex 异步工作的基础设施。',
    '## 好的 Loop 会自己停下来',
    '一个 loop 不成熟，通常不是因为它不够自动，而是因为它不知道什么时候停。',
    'Agent 如果一直试、一直改、一直绕，就会烧 token，也会制造噪音。便宜的 AI 时间如果没有交付条件，也会变成错误 diff 和维护成本。',
    '所以停止条件和交付条件一样重要。',
    '好的 loop 应该能主动说：',
    '这件事已经完成，验证结果如下。',
    '这件事还没完成，卡点是这个。',
    '这件事有两个方案，需要人选择。',
    '这件事风险超过边界，不能继续自动做。',
    '这件事测试无法证明正确，需要人工验收。',
    '这比盲目“继续”更重要。',
    'Loop engineering 不是追求 agent 永远不停，而是让 agent 在该推进时推进，在该停下时停下。',
    '## 驾驶员的下一层能力',
    'Codex 驾驶员的能力，不在于一直陪 agent 聊天。',
    '更高一层的能力是设计循环：',
    '把重复 prompt 变成 skill。',
    '把危险尝试放进 worktree。',
    '把固定检查变成自动步骤。',
    '把外部状态接进来。',
    '把复杂任务拆给 subagent。',
    '把人工介入放在真正值钱的位置。',
    '把最终交付设计成可以快速验收的结果。',
    '这样人就不再是每一轮 prompt 的发送者，而是 loop 的设计者。',
    'AI 的时间不是人的时间。不要用人的注意力去陪 agent 等待。',
    'Prompt 是让 Codex 做事。',
    'Goal 是定义完成状态。',
    'Loop 是让 Codex 在你不盯着的时候继续靠近完成状态。',
    '传奇驾驶员的重点不是更努力地 prompt。',
    '而是让系统替自己 prompt。',
    '## 参考',
    '- Addy Osmani: Loop Engineering：https://addyosmani.com/blog/loop-engineering/\n- snarktank/ralph：https://github.com/snarktank/ralph\n- Peter Steinberger on X: “You should be designing loops that prompt your agents.”：https://x.com/steipete/status/2063697162748260627\n- OpenAI Codex Goal mode / Automations / Worktrees / Skills / Subagents docs：https://developers.openai.com/codex/app/automations、https://developers.openai.com/codex/app/worktrees、https://developers.openai.com/codex/skills、https://developers.openai.com/codex/subagents',
  ],
  aiDisclosure:
    '本文由 AI 协助调研和整理表达，内容方向来自我对 Codex 驾驶员工作流和 Loop Engineering 的理解。',
  readingMinutes: 5,
  category: 'software',
  topic: 'ai-tools',
  series: 'codex-legendary-driver',
  tags: ['Codex', 'Loop Engineering', 'AI Coding', 'Workflow', 'Agent'],
  status: 'published',
} satisfies BlogPost
