import type { BlogPost } from '../../data/types'

export const codexLegendaryDriverOpenSourceSkillSet = {
  slug: 'codex-legendary-driver-open-source-skill-set',
  title: 'Codex 传奇驾驶员 04：我把自己的 Skill Set 开源了',
  date: '2026-06-24',
  excerpt:
    '我把自己目前在用的一套 Codex skill 工作流开源了。它不是一个包装得很完整的产品，而是一份可以同步、复用、继续修改的个人工作流集合。',
  content: [
    '我把自己目前在用的一套 Codex skill 集合开源了：[xinyu-s-skill-set](https://github.com/huangxinxinyu/xinyu-s-skill-set)。',
    '这个仓库很简单，名字叫 xinyu-s-skill-set。它的作用也很直接：把我现在用得比较多的一组 Codex skills 放在一起，方便在不同机器之间同步，也方便之后继续维护。',
    '对我来说，这不是一个“发布了一个大项目”的时刻，更像是把自己的工作流从本地目录里拿出来，变成一个可以被看见、可以被复用、可以被修改的版本。',
    '## 为什么要开源',
    '之前我写过一篇文章，说 skill 的价值不是制造仪式感，而是把好用的工作流复用起来。用 Codex 久了以后，我越来越觉得这件事应该落到文件和版本管理上。',
    '如果一个 skill 只躺在本机目录里，它当然也能用。但它很容易变成一个只存在于当前环境里的临时配置：换机器要重新找，改坏了不好回滚，别人也很难知道你到底是怎么用 Codex 的。',
    '放到 GitHub 之后，这套东西至少有了一个明确的位置。以后我想在新机器上恢复工作流，可以直接 clone；我想调整某个 skill，也能看到修改历史；别人如果对我的使用方式感兴趣，也可以直接看里面的 prompt、约束和流程。',
    '## 里面有什么',
    '目前仓库里放的是我正在使用或整理过的一组 workflow skills，包括 brainstorming、planning-with-files、grill-me、grill-with-docs、systematic-debugging、test-driven-development、receiving-code-review、using-git-worktrees、writing-skills、frontier-engineering-research、teach 和 using-foodism-test-env。',
    '这些 skill 覆盖的不是某一个单点能力，而是我日常和 Codex 协作时经常遇到的几类场景：需求没想清楚时先讨论，任务变长时用文件承接计划，遇到 bug 时系统化排查，做实现前先写测试，收到 review 时先验证再改，开始功能前把工作区隔离出来。',
    '也就是说，它更像是一组“我希望 Codex 怎么和我一起工作”的规则，而不是一组神奇命令。',
    '## 这套集合现在是什么状态',
    '我不想把它描述成一个成熟框架。它现在更像是我的个人工作流快照。',
    '有些 skill 已经用得比较多，有些还会继续调整触发条件和步骤。有些约束写得比较硬，是因为我在真实使用里踩过坑；有些地方还比较轻，是因为我不想让每个小任务都被流程拖重。',
    '仓库也刻意没有包含系统 skills。它主要保存我自己维护、自己会改、自己会迁移的部分。README 里也保留了一些现实状态，比如当时创建仓库时没有在本地 skill 目录里找到 job-search。',
    '这正是我想保留的感觉：它不是一个修饰过的展示项目，而是一个真实工作流的版本化记录。',
    '## 我希望它怎么被使用',
    '如果你也在用 Codex，我不觉得应该直接照搬我的全部 skill。更好的方式可能是把它当成一个参考，看一看别人是怎么描述任务边界、怎么限制 agent 行为、怎么把 review、debug、planning 这些流程写进 skill 里的。',
    '真正有价值的不是文件名，而是里面的工作方法。',
    '你可以复制其中一两个适合自己的，也可以把某些段落拆出来改成自己的版本。skill 最有意思的地方就在这里：它让经验不只是“我知道该怎么做”，而是变成可以被 agent 反复执行的工作流。',
    '## 之后会继续改',
    '这次开源不是结束，而是一个开始。',
    '之后我会继续把自己真正用得上的 workflow 放进去，也会把不够好用、太重、触发不准确的地方慢慢改掉。一个 skill 是否有价值，最后还是要看它能不能减少重复沟通、减少漏检、减少上下文丢失。',
    '所以这篇博客也只是一个简单记录：我把自己的 skill set 开源了。',
    '它现在在 GitHub 上，以后会跟着我的 Codex 使用方式一起变化。',
  ],
  aiDisclosure: '本文由 AI 协助整理表达，内容来自个人开源 Codex skill 集合的实践记录。',
  readingMinutes: 3,
  category: 'software',
  topic: 'ai-tools',
  series: 'codex-legendary-driver',
  tags: ['Codex', 'Skill', 'Open Source', 'Workflow'],
  status: 'published',
} satisfies BlogPost
