import type { BlogPost } from '../../data/types'

export const dokployLightweightPaasDeploymentTradeoffs = {
  slug: 'dokploy-lightweight-paas-deployment-tradeoffs',
  title: 'Dokploy：实习中接触到的轻量 PaaS 技术选型思路',
  date: '2026-06-16',
  excerpt:
    '从实习中使用 Dokploy 的视角，整理它在 Docker Compose、GitHub Actions、镜像 Registry、托管 PaaS 和自托管部署之间的位置，以及环境变量、密钥、文件和备份边界。',
  content: [
    '实习中我在用 Dokploy，对“部署平台”这件事有了一个更具体的理解。',
    '以前看部署选型，很容易把问题简化成几个选项：要么手写 Docker Compose，要么上 Vercel / Render 这类托管平台，要么更重一点走 Kubernetes。但 Dokploy 处在一个很有意思的位置：它不是把服务器抽象到完全不可见，也不是让你继续手动维护所有脚本，而是把一台或多台 Docker 服务器包装成一个轻量的 PaaS 控制面。',
    '所以这篇不是写“Dokploy 值不值得用”，而是从技术选型角度看：它把哪些复杂度收进平台，又把哪些责任留给使用者。',
    '## Dokploy 解决的是部署控制面',
    '如果已经会写 Docker Compose，服务本身怎么跑并不是最难的问题。真正麻烦的是围绕部署产生的一整套动作。',
    '代码从哪里拉？镜像在哪里构建？构建完推到哪个 registry？目标服务器怎么拉镜像？域名怎么绑定？证书谁来签？环境变量放在哪里？部署失败怎么看日志？数据库、volume、备份、远程服务器怎么管理？',
    '这些东西每一项单独看都不复杂，但放到多个项目、多台服务器、多次迭代里，就会变成维护成本。',
    'Dokploy 的价值就在这里。它不是替代 Docker，而是在 Docker、Traefik、Git、Registry、数据库、备份和监控之上放了一个控制面。你仍然知道应用跑在自己的服务器上，但很多重复部署动作不再靠手写脚本和临时命令维持。',
    '这也是我会把它放在 Docker Compose 和托管 PaaS 中间看的原因。',
    '## 一次部署链路不只是 git pull',
    '实习里用 Dokploy，我觉得最需要先看清的是完整链路。',
    '一个比较清晰的链路可以是：',
    '```text\n开发者 push 代码\n -> GitHub Actions 跑测试 / 构建\n -> 构建 Docker image\n -> push 到 GHCR / Docker Hub / 私有 Registry\n -> Dokploy 收到 webhook 或手动触发部署\n -> 目标服务器 pull image\n -> Docker / Compose / Stack 启动服务\n -> Traefik 接流量\n -> Dokploy 提供日志、部署记录、监控和回滚入口\n```',
    '这里 Dokploy 不一定要负责所有事情。它可以直接从 Git 仓库构建，也可以只负责消费 CI 已经构建好的镜像。两种方式背后的选型意义不一样。',
    '如果让 Dokploy 从 Git 构建，链路更短，适合简单项目：push 代码之后 Dokploy 拉代码、构建、部署，很多事情集中在一个控制面里。缺点是 CI 质量门禁、镜像可追踪性和构建复用可能弱一些。',
    '如果用 GitHub Actions 先构建镜像，再让 Dokploy 部署镜像，链路会更长，但边界更清楚：GitHub Actions 负责测试、构建、镜像标签、推送 registry；Dokploy 负责拉取指定镜像、注入环境配置、调度容器、接域名和流量、提供运行态可观测入口。',
    '这更像标准 CI/CD，也更容易定位问题。',
    '## 镜像是部署链路里的交付物',
    '在这条链路里，Docker image 才是比较稳定的交付物。',
    '代码仓库是源材料，GitHub Actions 是加工过程，Registry 是制品仓库，Dokploy 是运行控制面，服务器是执行环境。把这几个角色拆开之后，部署问题会更容易归因。',
    '测试失败，是 CI 问题。镜像构建失败，是 Dockerfile、build context 或依赖问题。镜像 push 失败，是 registry 凭据或权限问题。Dokploy pull 失败，是 registry 配置、网络或服务器登录问题。容器启动失败，是环境变量、启动命令、端口、volume 或运行时依赖问题。域名访问失败，可能是 Traefik、端口暴露、DNS 或防火墙问题。',
    '这就是为什么我觉得 Dokploy 不应该只被理解成“有 UI 的 Docker Compose”。它真正接入的是从代码到运行态的部署链路。',
    '## GitHub Actions 和 Dokploy 的分工',
    '我更倾向于把 GitHub Actions 和 Dokploy 看成两个不同阶段。',
    'GitHub Actions 负责 CI 和制品生产。它应该回答：代码能不能过测试？Docker image 能不能构建？镜像 tag 是否和 commit、branch、release 对得上？镜像能不能推到 registry？必要时，是否生成 provenance、SBOM 或其他制品信息？',
    'Dokploy 负责 CD 和运行态管理。它应该回答：目标服务使用哪个镜像？运行时环境变量是什么？容器挂载哪些 volume？域名和证书怎么接？部署失败在哪里？日志怎么看？需要回滚时从哪里操作？',
    '这两个阶段可以合在一起，但合在一起之后，很多边界会变模糊。比如构建失败和部署失败容易混在一个日志里，镜像 tag 可能不清晰，多个环境之间也更容易靠人工约定维持。',
    '把 CI 和部署控制面拆开，不是为了复杂，而是为了让每一步有明确责任。',
    '## 它和手写 Docker Compose 的差别',
    '手写 Docker Compose 最大的优点是透明。`docker-compose.yml` 在哪里，端口怎么映射，volume 挂到哪里，命令怎么执行，都非常直接。问题是透明不等于可维护。',
    '当项目多起来之后，手写方案通常会慢慢长出一堆隐形约定：某个目录专门放 `.env`，某个脚本负责部署，某个 Nginx 配置负责反代，某个 cron 负责备份，某个 README 记录服务器初始化步骤。只要这些约定没有被平台化，就很容易依赖某个人的记忆。',
    'Dokploy 做的是把这些约定收敛到 UI 和平台模型里。应用、Compose、域名、环境变量、日志、部署记录、数据库、备份、远程服务器，都能以更统一的方式管理。',
    '但代价是，你开始依赖 Dokploy 的控制面。出了问题时，不能只懂 Docker Compose，还要理解 Dokploy 怎么生成配置、怎么调用 Docker、怎么接 Traefik、怎么处理部署目录、镜像和 volume。',
    '## 它和托管 PaaS 的差别',
    'Vercel、Render、Railway、Fly.io 这类托管平台继续往上抽象。你不太需要关心宿主机、防火墙、Docker daemon、Traefik、系统更新、磁盘空间和备份目标。很多基础设施责任交给平台，换来的是更强约束和更高平台绑定。',
    'Dokploy 的方向不同。它更像是：服务器还是你的，Docker 还是你的，域名和数据也主要由你负责，只是部署控制面变得更像 PaaS。',
    '这带来的好处是自由度更高。你可以部署更普通的 Docker 服务，可以保留对服务器的控制，也更容易承接一些托管平台不太舒服的场景，比如多服务 Compose、私有网络、自定义数据库、长期运行的后台服务、比较特殊的反代或挂载需求。',
    '但它不会自动消除运维责任。自托管 PaaS 的关键不是“没有运维”，而是“把运维入口产品化”。',
    '## 环境变量不是密钥保险箱',
    '这一点我觉得在选型里很重要。',
    'Dokploy 支持在 UI 里配置环境变量。根据官方 Docker Compose 文档，这些变量默认会写到和 `docker-compose.yml` 同目录的 `.env` 文件里，而且不会自动注入容器；你需要在 Compose 里用 `env_file` 或 `${VAR_NAME}` 显式引用。',
    '这说明它更像部署配置管理，而不是完整的 secret management 系统。',
    '实际使用时，普通配置、数据库连接串、第三方 API key、SSH private key、云厂商 key，不应该被当成同一类东西。能用最小权限 token，就不要放主账号 key；能按环境拆分，就不要让 dev 和 prod 共用；能轮换，就不要让 key 长期不动。',
    'GitHub Actions 和 Dokploy 里的 secret 也应该分层。CI 需要的是“能构建和推送镜像”的权限，比如 registry token。运行平台需要的是“能拉取镜像和运行服务”的权限，比如运行时 API key、数据库连接串、registry pull 凭据。不要把它们混成同一个大 secret 池。',
    '部署平台让配置变得容易管理，但也会让敏感信息集中到一个地方。控制面账号、服务器权限、备份目标、Git provider 权限，都会成为安全边界的一部分。',
    '## 文件和 volume 的风险更容易被忽略',
    '环境变量至少还比较显眼，文件反而更容易被忽略。',
    '很多服务会依赖证书、service account json、私有配置文件、初始化脚本或上传目录。Dokploy 文档里提到，Docker Compose 场景下如果开启 Auto Deploy，每次部署会重新 `git clone`，直接挂载仓库里的相对路径可能导致文件在后续部署中丢失或变空。它建议把这类文件移到 File Mounts，持久化数据则根据场景选择 bind mount 或 Docker named volume。',
    '这背后其实是一个选型问题：文件到底属于代码、配置，还是运行时数据？',
    '代码应该进 Git。普通配置可以进环境变量或平台配置。敏感文件要考虑访问权限、备份范围和轮换方式。运行时数据则要考虑 volume、备份和恢复。把这些东西混在一起，短期看部署最快，长期看最容易出事故。',
    '## 备份也是 secret 的复制',
    'Dokploy 的备份文档里写到，它会备份 PostgreSQL 数据库和 `/etc/dokploy` 文件系统，压缩后上传到 S3 destination。',
    '这个能力很实用，但也意味着备份本身会变成敏感资产。如果控制面里保存了部署配置、项目元数据、连接信息、SSH key 相关信息或其他敏感材料，那么 S3 bucket 的权限、加密、生命周期、访问审计，就不能被当成次要配置。',
    '很多时候安全问题不是出在主系统，而是出在“复制出去的那份”。日志、备份、导出文件、临时目录，都可能比线上服务本身更容易被忽略。',
    '所以自托管 PaaS 的备份不能只问“能不能恢复”，还要问“谁能读到备份”。',
    '## 安全责任没有消失，只是换了位置',
    'Dokploy 的远程服务器安全文档里有一个很典型的提醒：Docker 会直接修改 `iptables`，因此可能绕过 UFW 规则，让容器暴露的端口仍然能从公网访问。',
    '这个例子很能说明问题。用了部署平台，不代表网络边界就自动安全。Dokploy 可以帮你管理部署，但宿主机、防火墙、Docker 暴露端口、SSH、系统更新、备份桶权限，仍然是使用者要理解的部分。',
    '托管 PaaS 把一部分责任交给平台。自托管 PaaS 则把这些责任留在自己手里，只是提供了更好的操作界面和默认路径。',
    '这不是缺点，而是选型事实。',
    '## 我现在会怎么理解 Dokploy',
    '如果只把 Dokploy 看成“开源版 Vercel”，我觉得会误解它。它更像是一个面向 Docker 服务器的轻量 PaaS 控制面。',
    '它适合的不是完全不想碰基础设施的人，而是已经接受自己拥有服务器、Docker、镜像、Registry 和数据责任，但不想把每个部署动作都散落在脚本、README、Nginx 配置和人工记忆里的人。',
    '从技术选型上看，Dokploy 把很多部署复杂度收敛了：Git 集成、构建、镜像部署、域名、证书、日志、环境变量、Compose、数据库、备份、监控、多服务器管理。与此同时，它也把 CI/CD 边界、控制面安全、密钥管理、volume 策略、备份权限和宿主机安全放到了更重要的位置。',
    '所以我对 Dokploy 的理解不是“更简单的部署工具”，而是“把 Docker 服务器产品化的一层控制面”。',
    '这层控制面能降低日常部署成本，但它不会替你做所有架构判断。真正的选型问题还是：你想把复杂度交给云平台，交给 Kubernetes，交给一堆脚本，还是收敛到 Dokploy 这样的自托管 PaaS 里。',
    '## 参考资料',
    '- Dokploy Applications：https://docs.dokploy.com/docs/core/applications\n- Dokploy Registry：https://docs.dokploy.com/docs/core/registry\n- Dokploy Docker Compose：https://docs.dokploy.com/docs/core/docker-compose\n- Dokploy Backups：https://docs.dokploy.com/docs/core/backups\n- Dokploy SSH Keys：https://docs.dokploy.com/docs/core/ssh-keys\n- Dokploy Remote Server Security：https://docs.dokploy.com/docs/core/remote-servers/security\n- Dokploy Architecture：https://docs.dokploy.com/docs/core/architecture\n- GitHub Actions Publishing Docker images：https://docs.github.com/en/actions/tutorials/publish-packages/publish-docker-images',
  ],
  aiDisclosure:
    '本文由 AI 协助整理表达，内容来自实习中对 Dokploy 的使用观察、公开文档调研和个人对部署选型的理解。',
  readingMinutes: 6,
  category: 'software',
  tags: ['Dokploy', 'Docker', 'PaaS', 'GitHub Actions', 'DevOps'],
  status: 'published',
} satisfies BlogPost
