import type { BlogPost } from '../../data/types'

export const internshipDaytonaAgentWorkspace = {
  slug: 'internship-daytona-agent-workspace',
  title: '实习项目里用到 Daytona 后，我重新理解了 agent sandbox',
  date: '2026-06-05',
  excerpt:
    '从实习项目里的 agent workspace 场景出发，整理 Daytona 这类 sandbox 为什么不只是远程跑代码，而是在把 agent 的执行现场产品化。',
  content: [
    '最近实习项目里用到了 Daytona。最开始我对它的理解很简单：这是一个可以通过 API 创建和控制的 sandbox，用来让 agent 在隔离环境里跑代码、装依赖、执行命令。',
    '但用下来以后，我觉得更值得写的不是“Daytona 能远程跑代码”，而是它把 agent 的执行现场做成了一个可以被管理、恢复和计费的基础设施单元。换句话说，它不只是 sandbox，更接近 agent workspace。',
    '## Daytona 在 agent 系统里的位置',
    '在 agent 应用里，LLM 负责判断要做什么，工具调用负责连接外部能力，而 sandbox 负责把事情真正跑起来。尤其是 coding agent 或自动化 agent，它不能只停留在生成文本阶段。它需要拉代码、改文件、安装依赖、跑测试、看日志、生成产物。这些动作如果直接发生在主服务、本机或共享环境里，风险和运维复杂度都会很高。',
    'Daytona 这类工具的定位，就在这个执行层。它本身不是 agent brain，也不是 LLM 编排框架。agent 负责决定下一步做什么，Daytona 负责提供一个隔离、可控、可生命周期管理的执行环境。',
    '一个典型流程大概是：',
    '```text\n用户请求\n  ↓\nAgent / App Server 理解任务\n  ↓\n创建或恢复一个 Daytona sandbox\n  ↓\n在 workspace 里读写文件、安装依赖、执行命令\n  ↓\n把日志、文件、产物返回给 agent\n  ↓\n停止、归档、恢复或销毁 workspace\n```',
    '在我的实习项目语境里，我更愿意把它理解成 agent workspace：agent 不只是临时执行一条命令，而是在一个隔离的工作目录里持续完成任务，包括准备环境、读写文件、运行脚本、保留产物，以及在需要时恢复之前的工作现场。',
    '## 从 sandbox 到 workspace',
    '我现在会把 agent workspace 抽象成这几个部分：',
    '- Isolated runtime：agent 可以执行代码，但不会污染主服务或用户本机。\n- Filesystem：agent 有自己的工作目录，可以读写文件、生成产物、保存日志。\n- Lifecycle：workspace 可以创建、启动、停止、恢复、归档、销毁。\n- Access control：网络、secret、资源、文件访问需要被控制。\n- Recovery：任务失败或系统重启后，尽量恢复环境和文件现场。',
    'sandbox 强调的是隔离。workspace 强调的是任务连续性。',
    '如果只是跑一段代码，很多东西都能做：本地 Docker、CI runner、云函数，甚至自己起一个容器服务。但 agent workspace 的问题不只是“能不能跑”，而是“跑到一半之后现场还在不在”。',
    '对 agent 来说，任务经常不是一次性命令。它可能先 clone 一个 repo，再安装依赖，跑测试，发现失败，改代码，再跑一次。如果中间失败、超时、重启，所有东西都从空环境重新开始，agent 就很难承担真正的长任务。',
    '所以状态恢复变得非常关键。',
    '## 最重要的是状态恢复',
    '这里的状态至少分三类。',
    '第一类是环境状态，比如基础镜像、语言版本、系统依赖、工具链。Daytona 的 snapshot 可以把预配置环境作为模板，后续创建 sandbox 时复用。这个能力解决的是“每次启动是不是同一个环境”。',
    '第二类是文件状态，比如 agent 改过的代码、生成的中间文件、测试日志、构建产物。sandbox 的文件系统、volume、archive 这类能力，解决的是“执行现场能不能留下来”。Daytona 文档里也明确提到，stopped sandbox 会保留文件系统但清掉内存，archive 则可以把整个文件系统状态放到更低成本的对象存储里，之后再启动。',
    '第三类是任务状态，比如 agent 当前做到第几步、为什么失败、下一步应该尝试什么、哪些外部 API 已经调用过。这个通常不应该完全交给 sandbox，而应该由上层 app server 或数据库管理。',
    '所以更准确地说，sandbox persistence 不是完整的 task persistence。它保存执行现场，但不替代任务编排层。可靠的 agent 系统，应该是 app state 和 sandbox state 的组合：app 记录任务语义，sandbox 保存执行现场。',
    '这也是我觉得 Daytona 最有意思的地方。安全隔离是入场券，但状态恢复决定了 agent 能不能真的做长任务。',
    '## 和 Docker、CI、Codespaces 的区别',
    'Docker 解决的是运行单元。它很适合本地验证 demo，但如果要做成多人、多任务、可恢复、可计费的 agent 产品，还要自己处理环境生命周期、文件持久化、并发调度、网络限制、成本核算和失败现场保留。',
    'CI runner 解决的是流水线执行。它适合固定流程，比如构建、测试、部署，但不太适合 agent 这种低延迟、交互式、状态不断变化的任务。',
    'Codespaces、Gitpod 这类产品更偏人类开发环境。它们的核心体验是让人打开 IDE 写代码。而 Daytona、E2B 这类 sandbox 更偏程序化调用：agent 或 app server 通过 API 创建环境、执行动作、拿回结果。',
    '所以 Daytona 的价值不是“比 Docker 更会跑代码”，而是把运行环境上面的生命周期抽象产品化了。',
    '## 沙盒租户模式',
    '这件事往商业模式上走，就会变成一个很有意思的趋势：agent sandbox tenant。',
    '传统 SaaS 里的 tenant 往往是公司、团队或用户。但在 agent sandbox 里，tenant 的粒度可以更细。一个用户可以有一个 workspace，一个项目可以有一个 workspace，一次 agent task 也可以有一个临时 workspace。',
    '短任务里，一个 sandbox 可以对应一次 agent task；长期 coding assistant 里，一个 sandbox 可以对应一个 project workspace。无论粒度怎么选，它本质上都是一个可隔离、可恢复、可计费的 agent workspace。',
    '这时候平台卖的就不只是 compute。',
    'running sandbox 可以按 CPU、内存、时长计费；stopped workspace 可以按磁盘或保留时间计费；archived workspace 可以按对象存储计费；volume 可以按持久数据计费；并发、网络控制、secret 管理、审计能力，则会变成更偏企业和平台型客户的付费点。',
    '也就是说，agent sandbox 的商业模式，不只是卖算力，而是按“可恢复工作空间”的生命周期计费。',
    '## 结尾',
    '这也是为什么我觉得 Daytona 值得关注。它不是唯一做这件事的产品，也不需要把它写成某种确定性的未来。但它是一个很好的切口：通过它可以看到，agent 应用需要的基础设施正在从“临时执行代码”往“管理执行现场”演化。',
    '对 agent 来说，真正有价值的不是安全地跑一段代码，而是安全地拥有一个可以继续工作的现场。',
    '这可能就是 sandbox 到 workspace 的变化。',
    '参考核对：Daytona 官方文档中的 Sandboxes、Sandbox Management、Snapshots 和 Volumes 页面，分别对应隔离运行环境、生命周期管理、环境模板和持久存储能力。',
  ],
  aiDisclosure: '本文由 AI 协助整理表达，内容来自个人实习项目经验和 Daytona 官方文档核对。',
  readingMinutes: 6,
  category: 'software',
  featured: true,
  tags: ['实习记录', 'Daytona', 'Agent', 'Sandbox'],
  status: 'published',
} satisfies BlogPost
