import type { BlogPost } from '../../data/types'

export const internshipAgentMemoryGovernance = {
  slug: 'internship-agent-memory-governance',
  title: '实习中设计 memory 板块后，我意识到记忆系统的难点不是“记住更多”',
  date: '2026-06-17',
  excerpt:
    '从实习里 memory 板块的设计出发，整理 agent memory 的更新链路、类型策略、冲突处理和评测方法。',
  content: [
    '最近实习中讨论到 agent 的 memory 板块。最开始我很容易把 memory 理解成“让 agent 记住更多东西”：用户说过什么、偏好是什么、之前做过什么任务，下次再对话时把这些信息拿回来。',
    '但继续往下想，我发现 memory 真正难的地方不在存储，而在治理。一个可上线的 memory 系统不能只回答“能不能记住”，还要回答：这条记忆从哪里来，现在还成不成立，和旧记忆冲突时应该信谁，用了以后效果到底有没有变好。',
    '换句话说，memory 不是聊天记录的压缩版，而是一套需要 extraction、policy、conflict handling 和 evaluation 的系统能力。',
    '## Memory 不是历史聊天记录',
    '历史聊天记录是原始材料，memory 是从材料里抽出来、结构化之后、未来可能会影响 agent 行为的上下文。',
    '比如用户说：“以后回答我直接给结论，不要展开太多。”',
    '这句话可以进入聊天记录，但如果要变成 memory，系统还要知道它是什么类型的记忆。它不是用户身份，不是业务状态，也不是项目事实，而是一个回答风格偏好。它可能适合长期保存，也可能只适合当前任务。',
    '这就是 memory 和 chat history 的区别。chat history 主要回答“之前发生了什么”，memory 还要回答“未来是否应该继续使用这条信息”。',
    '业内产品也在往这个方向走。OpenAI 和 Claude 的 memory 都不是单纯把历史对话塞回上下文，而是提供可查看、可编辑、可删除的 memory summary 或 project memory。这个设计背后的共识是：memory 不能是黑盒。用户需要知道系统记住了什么，也应该能纠正它。',
    '## 更新链路：LLM 抽取，后端治理',
    '我现在更认可的一条链路是：',
    '```text\nconversation / event\n -> LLM extracts memory candidates\n -> backend retrieves related old memories\n -> LLM judges relation\n -> backend policy decides action\n -> memory store writes version, status and audit log\n```',
    'LLM 适合做 extraction。它能从自然语言里抽出候选 memory，并给出 type、key、value、evidence 和 confidence。',
    '比如：',
    '```json\n{\n  "type": "preference",\n  "key": "response_style",\n  "value": "concise_direct_answers",\n  "evidence": "以后回答我直接给结论，不要展开太多",\n  "confidence": 0.9\n}\n```',
    '但 LLM 不应该直接决定这条 memory 是否成为系统事实。因为这已经不是语言理解问题，而是系统治理问题。',
    '后端需要判断：这个类型能不能自动写入？scope 是 global、project 还是 conversation？是否敏感？是否和旧 memory 冲突？是否需要用户确认？最终是 create、update、supersede、ignore，还是 ask confirmation？',
    '所以更准确的边界是：LLM 负责提出候选和语义关系，后端负责策略裁决和状态迁移。',
    '## 不同类型的 memory 要走不同 policy',
    'memory 不能只分成 important 和 unimportant。更合理的做法是按类型治理。',
    '偏好类 memory，比如回答风格、语言偏好、工具偏好，可以相对自动地更新。用户最近明确说“以后直接给结论”，那旧的“喜欢详细解释”可以被 supersede，但旧记录不应该直接消失，而是保留版本和来源。',
    '用户事实类 memory，比如城市、职业、学校、角色，要更谨慎。它们会变化，但不一定是简单覆盖。“我在上海”和“我搬到杭州了”可能意味着旧事实过期，新事实生效；这时更好的方式是给旧 memory 加 `valid_to`，给新 memory 加 `valid_from`。',
    '项目上下文类 memory 必须绑定 scope。“这个项目用 LangGraph 和 Postgres”只应该在当前项目里生效，不应该污染用户的全局 memory。并且项目事实应该优先相信代码、配置和文档，而不是聊天里的随口描述。',
    '业务状态类 memory 最危险。用户说“我已经付费了”，系统不能直接把 subscription status 写成 paid。LLM 最多抽出“用户声称已付费”，真正的支付状态必须查 billing database、订单系统或其他 source of truth。',
    '还有 procedural instruction，比如“以后写博客先问我核心论点”。这类 memory 很有用，但必须有 scope。否则一次任务中的流程要求会变成全局行为，反而污染后续 agent 表现。',
    '## 冲突处理：不是让模型自己覆盖',
    '新旧 memory 冲突时，我认为比较专业的做法是：',
    '```text\nbackend 找出相关旧 memory\nLLM 判断 candidate 和旧 memory 的关系\nbackend 按 policy 写回\n```',
    '后端找 candidate memory 时不能只靠 embedding。它应该组合 user_id、scope、type、key、entity、recency、status 和 semantic similarity。否则相关旧记忆找不全，LLM 也无法判断冲突。',
    'LLM 判断的是关系，比如 duplicate、reinforce、conflict、supersede、unrelated。它可以输出：',
    '```json\n{\n  "relation": "conflict",\n  "confidence": 0.86,\n  "reason": "Both memories describe user\'s default answer verbosity with opposite preferences."\n}\n```',
    '但最终动作还是后端决定。',
    '如果这是 preference，policy 可以是 newer_wins，于是旧 memory 变成 superseded，新 memory 变成 active。',
    '如果这是 profile_fact，policy 可能是 temporal_supersede 或 ask_when_uncertain。',
    '如果这是 business_state，policy 必须是 source_of_truth。用户说自己已付费，不能覆盖数据库事实，只能触发系统查询。',
    '这也是我现在对 memory conflict 的理解：LLM 可以做 semantic judge，但 backend 必须做 policy engine。',
    '## Policy 至少要回答六个问题',
    '一个 memory policy 至少要回答：这条 memory 能不能写？写到哪个 scope？信不信这个来源？和旧 memory 冲突时谁赢？是否需要用户确认？未来检索时能不能用？',
    '我会把 policy 拆成几类。',
    '- Write policy 决定什么能写入。preference 可以自动写，business_state 不能从对话直接写，sensitive memory 默认不长期保存，inferred memory 不能当事实。\n- Scope policy 决定 memory 在哪里生效。global user memory、project memory、conversation memory 和 org/team memory 不能混在一起。\n- Source trust policy 决定来源权重。system database 高于 user confirmation，高于 explicit user statement，高于 model inference。\n- Conflict policy 决定冲突时怎么处理。preference 可以 newer_wins，profile_fact 可以 temporal supersede，business_state 必须 source of truth，sensitive memory 需要 explicit confirmation。\n- Lifecycle policy 决定 memory 状态。memory 不应该只有存在和删除，还应该有 active、superseded、expired、rejected、needs_confirmation、archived。\n- Retrieval policy 决定什么时候使用 memory。写进去不代表每次都塞进 prompt。检索时应该优先同 scope、active、recent、high trust 的 memory，并控制 token budget。',
    '这套东西看起来比“存一段 summary”复杂很多，但如果没有 policy，memory 很快会变成不可解释的上下文污染。',
    '## Memory 评测不能只看有没有召回',
    '另一个重要问题是：memory 用了以后到底有没有变好？',
    '我觉得至少要分四层评测。',
    '第一层是 extraction eval。模型有没有正确抽出该记的内容？有没有把不该记的敏感信息写进去？有没有把推断当事实？有没有 evidence span？',
    '第二层是 retrieval eval。需要用 memory 时，系统有没有召回正确 memory？有没有召回过期或冲突 memory？Hit@K、MRR、token cost、latency 都要看。',
    '第三层是 end-to-end eval。加入 memory 后，agent 最终回答是否更准确、更一致、更个性化？任务完成率有没有提升？有没有因为错误 memory 反而退化？',
    '第四层是 conflict handling eval。新旧 memory 冲突时，系统是否正确覆盖、确认、拒绝或查询 source of truth？',
    '评测集里需要故意放冲突样例。比如用户以前喜欢详细解释，现在要求直接给结论；用户以前在上海，现在搬到杭州；用户说自己已付款，但数据库显示未付款；用户在一个项目里要求用 Python，但另一个项目用 TypeScript。',
    '如果只测普通事实召回，memory 系统会显得很好。但真正上线后，问题往往出在 stale memory、scope 泄漏、错误覆盖和隐式冲突上。',
    '## 业内实践给我的校验',
    '调研 OpenAI、Claude、LangGraph、LlamaIndex、Graphiti、Mem0、LoCoMo 和 LongMemEval 之后，我最大的感受是：成熟 memory 系统正在从 prompt trick 变成状态治理系统。',
    'OpenAI 和 Claude 让我看到产品层的重点：memory 必须可见、可编辑、可删除，用户要能知道系统记住了什么。',
    'LangGraph 和 LlamaIndex 让我看到框架层的重点：memory 要区分 short-term、long-term、semantic、episodic、procedural，也要区分 profile、collection、block 这类不同组织方式。',
    'Graphiti 和 Mem0 让我看到基础设施层的重点：更新 memory 不应该只是 overwrite。更稳的方式是保留 source、timestamp、validity window、version 和 invalidation，把旧事实变成历史，而不是直接抹掉。',
    'LoCoMo 和 LongMemEval 这类 benchmark 则提醒我：memory 评测不只是单轮问答准确率，还要测多 session 推理、时间推理、知识更新和冲突处理。',
    '这些资料最终都指向同一个判断：memory 不是越多越好，而是要可信地记住。',
    '## 结尾',
    '现在我会把 agent memory 理解成一套长期上下文治理系统。',
    'LLM 的能力很重要，因为它负责从自然语言里抽取候选 memory，也负责判断新旧 memory 的语义关系。但真正决定系统可靠性的，是后端有没有 policy、source trust、scope、lifecycle、audit 和 eval。',
    '如果没有这些东西，memory 只是把更多不确定的信息塞进上下文。短期看起来更个性化，长期一定会遇到 stale、conflict、privacy 和 hallucination 的问题。',
    '所以这次设计 memory 板块后，我最大的收获不是“agent 应该记住用户”，而是：一个好的 memory 系统，必须知道什么该记、什么不该记、什么已经过期、什么需要确认，以及用了这条记忆之后结果有没有真的变好。',
    '参考核对：OpenAI Memory FAQ、Claude Memory、LangGraph Memory docs、LlamaIndex Memory Blocks、Graphiti temporal knowledge graph、Mem0 Memory Evaluation、LoCoMo、LongMemEval。',
  ],
  aiDisclosure: '本文由 AI 协助整理表达，内容来自个人实习中的 memory 设计思考和公开资料调研。',
  readingMinutes: 7,
  category: 'software',
  topic: 'internship-summary',
  tags: ['实习总结', 'Agent', 'Memory', 'Eval'],
  status: 'published',
} satisfies BlogPost
