import type { BlogPost } from '../../data/types'

export const jevDecisionModel = {
  slug: 'jev-decision-model',
  title: 'Jev：把判断从 LLM 里拆出来',
  date: '2026-09-20',
  excerpt:
    '大模型还在沿着推理、多模态和 Agent 扩展，Jev 却放弃文本生成，只输出有限选项及其概率。官方给出的服务延迟是 70–500ms，输入每百万 token 0.042 美元、输出免费。本文再从 RLCD 与一个 100-tool Agent 实验，讨论这种判断模型能做什么，以及它可能给 Agent 带来的新分工。',
  content: [
    '最近两年的新模型发布很容易归到几条主线上：参数继续增加，推理时间继续拉长，输入从文字扩展到图片、视频和声音，模型再接上工具成为 Agent。衡量模型进步的方式也很接近，看它能不能完成更复杂、更开放的任务。',
    'Jev 的方向窄得多。TypeSafe 在 2026 年 9 月把它称为第一个公开的 System One Model。它不写文章，不生成代码，也不负责和人聊天。开发者需要在调用前把答案范围写好，Jev 只负责判断哪个答案更可能成立。',
    '我第一次看到这个接口时，感觉它很像一个做得更灵活的分类器，很难理解为什么需要单独发明一类模型。读完官方文档和这几天出现的独立测试后，我开始从系统拆分理解它：我们现在把理解、判断和生成都塞进一次 LLM 调用里，Jev 尝试把其中的判断单独拿出来。',
    '这个拆分能不能成立，决定了 Jev 最后会成为一种新模型，还是一个短暂的新 API。',
    '## 一款要先写好答案范围的模型',
    'Jev 和 LLM 仍然有不少共同点。它们都能读取自然语言和程序提供的上下文，也都依靠训练中学到的语义能力处理没有办法写成普通规则的问题。TypeSafe 的官方介绍同样把预训练语言模型画在 RLCD 训练路径的起点。[官方 AI primer](https://docs.typesafe.ai/introduction/machine-learning-primer.md)',
    '差别主要出现在输出端。',
    'LLM 接收上下文后逐个 token 生成字符串。这个字符串可以是解释和代码，也可以是工具调用或 JSON。Jev 接收一份 `state` 和一组 typed questions，返回预先声明的值及其概率。目前公开接口有三种问题：',
    '- `Noul`：一个命题成立的概率，比如“任务是否已经完成”。\n- `Choice`：从有限选项中选择一个，比如“下一步调用哪个工具”。\n- `Score`：在有顺序的等级中评分，比如“风险属于低、中、高还是严重”。',
    '公开接口对应一条从 state 到普通代码的执行链：',
    '```text\n程序状态 state\n  ↓\n一组预先声明的问题 Noul / Choice / Score\n  ↓\n多个问题共享 state，并行计算\n  ↓\n选项、概率分布、置信度\n  ↓\n普通代码根据阈值分支、执行或升级处理\n```',
    '这是一张接口层面的结构图，不代表 Jev 已经公开了完整神经网络架构。TypeSafe 只披露了“新架构”和 parallel sampler，没有公布 backbone 和参数量，也没有公开权重以及 sampler 的实现。现阶段可以确定的是它怎样被调用，不能确定模型内部到底长什么样。[Jev 发布文](https://typesafe.ai/blog/introducing-system-one-models-and-jev)',
    '## 先看速度：官方给出的延迟是 70–500ms',
    'Jev 1.13 当前的公开价格是每百万输入 token 0.042 美元，输出免费。TypeSafe 给出的服务延迟范围是 70–500ms。[模型与价格文档](https://docs.typesafe.ai/models)',
    '这个区间不是 Jev 与某款 LLM 在相同任务、相同地区和相同并发下的 head-to-head 结果，不能直接写成“比 LLM 快多少倍”。但它已经说明了 Jev 想占据的位置：判断不能成为 Agent 每一步里最慢、最贵的调用。',
    '它有机会更快，原因也不神秘。LLM 要逐 token 解码一段答案，输出越长，计算和等待时间通常越长。Jev 的答案范围已经确定，它返回选项概率，不需要写出推理过程和自然语言解释。多个问题还可以共享同一份 `state`，在一次请求中并行完成。',
    '一份独立校准审计把同一个问题单独发送，也和 10 个普通问题一起发送，随后又与 15 个普通和对抗问题一起发送。250 条样本中的 p50 延迟分别是 257ms、264ms 和 271ms。问题数量从 1 个增加到 16 个，只增加了 14ms。这至少支持了“同一状态下追加独立问题很便宜”这项产品能力。[Jev calibration audit](https://github.com/jujumilk3/jev-calibration-audit/blob/main/FINDINGS.md)',
    '这些信息还不足以建立很深的成本判断。模型有多大、部署在什么硬件上都不知道；一次请求实际使用多少算力，当前价格是否带有早期补贴，也没有公开。TypeSafe 自己也承认，公开价格无法证明没有补贴。文章可以解释 Jev 少做了哪些工作，无法从 `$0.042 / MTok` 倒推出它的训练和推理效率。',
    '训练速度同样是未知数。RLCD 的名字听起来像一条更直接的训练路线，目前没有训练时长、算力或收敛数据可以比较。',
    '## 输出不会越界，判断仍然会错',
    'TypeSafe 在发布 Jev 时使用了“cannot hallucinate”这个说法。放到工程里看，它保证的是输出空间。',
    '假设一个 `Choice` 只有 `search_flights`、`book_flight` 和 `send_email` 三个选项，Jev 不会突然返回 `delete_database`，也不会在 JSON 外面多写一段解释。程序总能拿到 schema 允许的值。LLM 即使开启 structured output，背后仍在生成 token，还需要解析和校验；Jev 的输出从模型层面就被限制住了。',
    '这个保证没有覆盖语义正确性。Jev 完全可能在三个合法工具中选错一个，也可能给错误选择很高的概率。TrueStandard 的 108 条 claim-grounding 测试里，Jev 在最难一档仍然判断错了 4 次。它没有捏造第四种输出，但选中的合法答案并不正确。[TrueStandard 测试](https://truestandard.ai/blog/jev-accuracy-tested)',
    '所以我更愿意把它理解成“受约束的错误”。自由文本里可能出现的编造、跑题和格式错误被消掉了，剩下的是程序更容易记录和处理的选择错误。失败变得规整了一些，没有因此消失。',
    '## RLCD 希望让概率能进入程序',
    'TypeSafe 把 Jev 的训练方法称为 RLCD，全称 Reinforcement Learning for Calibrated Decisions。官方给出的目标很直白：模型返回的不只是答案，还要让概率与长期正确率相符。一批概率为 0.8 的判断，理想情况下应当约有 80% 最终被证明正确。',
    '这和 accuracy 是两回事。一个模型可以在 90% 的样本上答对，却在剩下 10% 上同样表现得非常自信；这样的模型很难无人值守。另一个模型可能只答对 85%，但能把容易出错的案例放在低置信度区间，系统便可以把那部分交给 LLM 或人工。',
    'RLCD 因此关系到 Jev 能不能真正进入控制流。程序可以写出这样的策略：',
    '```text\n高置信度    自动执行\n中间区间    交给 LLM 重新处理\n低置信度    拒绝执行或转人工\n```',
    '这里的问题在于，校准不是写在模型名字上的永久属性。',
    '一份针对 Jev 1.13 的独立审计测试了 300 条信息不足的问题。候选项里包含 `unknown` 时，Jev 有 95% 会选择不知道，ECE 为 0.023，已经接近这个样本量的噪声底。研究者删掉 `unknown` 后，Jev 没有通过降低置信度提醒开发者“这里缺了一个答案”，而是以平均 0.793 的置信度选择剩余选项，准确率为 0。',
    '同一份审计还发现，把同一个判断写成 `Noul` 或二选一 `Choice`，两边概率平均相差 0.125；16.3% 的案例相差超过 0.2。交换两个 Choice 选项的顺序影响却很小，400 条样本里没有一次改变最终选择。',
    '另一个 108 条 claim-grounding 对照中，Jev、Gemini Flash Lite 和 Claude Haiku 的 ECE 分别是 0.066、0.061 和 0.067，在这个样本量下没有明显差异。Jev 在最难的 near-miss 上准确率和 Brier score 更好，这是一项具体任务优势，还不足以证明 RLCD 普遍比 LLM 更会表达概率。',
    '截至本文写作时，TypeSafe 没有公开 RLCD 的 reward 和 loss，训练数据、算法论文和校准曲线也没有公开。它现在更像一项明确的训练目标和产品承诺。真正使用时，阈值要在自己的数据和问题写法上重新测，同时固定候选项与模型版本。少写一个 `none of the above`，整套自动化就可能从“知道自己不知道”变成“在错误答案里自信地挑一个”。',
    '## 把 Jev 放进一个 100-tool Agent',
    '目前最容易理解 Jev 的方式，是看它怎样进入已有 Agent。',
    '开源项目 [`vinilana/jev-eval-agent`](https://github.com/vinilana/jev-eval-agent) 做了一个模拟个人助理，包含 100 个工具，覆盖出行、日历和通信，以及费用与转账。项目比较了两种运行方式：',
    '- `llm-direct`：LLM 每一轮看到全部 100 个工具，自己选择工具并填写参数。\n- `jev-classifier`：Jev 先从 100 个工具中选一个，LLM 只看到中选工具的 schema，随后填写参数。',
    '所有工具和数据都是模拟的，项目只有 6 个任务，它不是生产案例。其中一条保存下来的真实 trace 很适合观察两类模型怎样分工。',
    '用户的请求翻译成中文是：',
    '“周五下午两点要在圣保罗开会。找一班从里约早上出发的最便宜航班，替我预订，再把航班放进日历。”',
    '第一轮状态可以简化成：',
    '```text\nuser_request:\n  周五 14:00 在圣保罗开会；寻找里约早上出发的最便宜航班，预订并写入日历\n\nactions_taken: []\n\navailable_tools:\n  flights_search, flights_book, calendar_create_event,\n  calendar_create_meeting, contacts_get, ... 共 100 个\n\nquestions:\n  next_tool: 下一步应调用哪个工具？\n  done: 用户要求的动作是否已经全部完成？\n```',
    'Jev 第一次返回 `flights_search`，选择概率为 1.00，confidence 为 0.99，`done` 为 0.02。LLM 此时只读取航班搜索工具，生成出发地与目的地，以及日期和最晚起飞时间。',
    '搜索结果回来后，新的 state 带上已经执行的动作和航班列表。Jev 接下来依次选择：',
    '```text\nflights_book          p=0.96  confidence=0.95\ncalendar_create_event p=0.90  confidence=0.89\nrespond_to_user       p=0.75  confidence=0.73\n```',
    'LLM 在每一轮只负责给当前工具填写参数。最后一轮没有工具需要执行，它生成给用户的自然语言回复。整个任务里，Jev 没有搜索或预订航班，也没有写日历和组织最终答案。它做的是四次“现在该走哪一条分支”。',
    '这条运行中，Jev 方案调用了 3 个正确工具，完成度为 100%，LLM 共读取 3,312 个输入 token，总耗时 6.3 秒。相同模型直接面对 100 个工具时，只完成了航班搜索，然后向用户追问仓库里其实已经提供的信息；完成度为 33%，读取 10,334 个输入 token，总耗时 8.4 秒。',
    '单例很好看，完整结果要复杂一些。我汇总了仓库中 7 个模型、6 个任务的 42 组配对运行。不同模型的 LLM 平均输入量从约 1.7 万至 6.2 万 token 降到约 0.4 万至 0.8 万；平均任务完成度则从 98.4% 降到 92.1%，两种模式的整体效率几乎相同。',
    '这个实验说明了 Jev 可以搬走哪一部分工作：LLM 不用在每一轮重新阅读整本工具目录。它也展示了新的故障点。Jev 一旦选错工具，LLM 连正确工具的 schema 都看不到。上下文更短了，路由层本身也需要单独做 eval。',
    '## 哪些工作现在可以尝试搬过去',
    '我会用三个条件判断一个任务是否适合 Jev：候选答案能提前写出来，判断所需证据能放进当前 `state`，系统最后需要的是选择或概率。',
    '这三个条件同时成立时，很多现有 LLM 调用都可以测试 Jev：Agent 的工具和 skill 选择与客服工单分流；内容审核和 RAG 候选重排；引用是否支持 claim、回答是否通过质量门槛，以及 agent trace 的完成度判断。',
    '已经有人把 Jev 用作 agent evaluator。在 5 条固定 weather-agent trace、每条重复评价 100 次的小实验中，Jev 的 pass/fail 结果全部匹配唯一一位人工标注者，连续质量分数的方差也低于三种 LLM judge。数据只有 5 条，无法据此给模型排名；它至少说明 LLM-as-a-judge 这类最终只消费分数的工作，与 Jev 的输出形态很接近。[Jev as a judge](https://github.com/danielgshea/jev-as-a-judge)',
    '股票买卖距离直接搬到 Jev 还很远，即使输出可以写成 `buy / hold / sell` 三选一。交易决策依赖实时行情和时序特征，还需要数值计算、持仓状态与风险预算，并经过策略回测。Jev 当前只接收文本状态，也不维护账户记忆。一个比较合理的位置，是让上游系统先计算指标，再让 Jev 判断“这组信号是否触发已经定义好的减仓条件”。它没有因此获得发现交易策略或自主承担资金风险的能力。',
    '有限选项只约束输出，不会把一个高风险问题自动变简单。',
    '## 既定判断场景里也有明显短板',
    'Jev 的官方 jaggedness 文档列得很坦白。当前版本对数学和计数，以及日期比较和多跳间接关系不稳定；无关上下文会伤害结果；对抗内容可能影响判断；同一个问题换一种结构，概率不保证满足人预期的恒等关系。[Jev 1.13 known jaggedness](https://docs.typesafe.ai/model-jaggedness/jev-1.13)',
    '结合独立测试，我觉得实际使用时尤其要留意几件事。',
    '第一，候选项的设计属于模型输入的一部分。漏掉 `unknown`、`other` 或 `no_action`，Jev 可能被迫在错误答案中选择。',
    '第二，概率阈值跟着具体问题走。同一语义从 Noul 改成 Choice，原有阈值未必还能用。问题文本与 criteria、选项和模型版本应该像代码一样进入版本控制和回归测试。',
    '第三，Jev 不提供自然语言解释。速度和确定输出来自它放弃的生成能力，出错时也少了一份可以阅读的 reasoning。开发者需要结合原始 state 与概率分布，再看相邻问题和人工标注来排查。',
    '第四，它不会创造缺失的候选方案。工具目录里没有正确工具，或检索阶段没有找回正确文档；上游指标没有表达真正风险时，Jev 只能在错误集合里做得更确定。',
    '## 它可能怎样进入下一代 Agent',
    '如果这类模型继续发展，我觉得最值得观察的方向是 Agent 内部的模型分工。',
    '今天很多 Agent 让同一个 LLM 读取状态和规划任务，随后选择工具、填写参数，还要检查结果、判断是否完成，再生成回复。Jev 提供了另一种组合方式：频繁而封闭的判断交给决策模型，遇到开放式规划和解释，以及内容生成时再调用 LLM，普通代码继续保存状态并执行工具，同时控制权限。',
    'Memory 也可以按这个方式拆。Jev 当前没有持久记忆，API 每次只读取调用方传入的 state。未来它可以判断一条信息值不值得写入记忆，当前任务需要取回哪一段，以及哪些内容已经过期。真正的存储仍在数据库里，摘要和记忆重写仍需要生成模型。Jev 管的是存取决策。',
    '它也可能成为贯穿 Agent 运行过程的检查层。工具执行前判断是否越权，执行后判断结果是否满足预期，进入下一步前判断是否需要用户确认。相比只在最终答案上加一层 guardrail，这种判断会分布在整条执行链路里。',
    '端侧是一个有吸引力但证据不足的方向。非生成式模型如果能够做得更小，设备可以先在本地完成简单判断，只在需要时唤醒云端 LLM。Jev 没有公开模型尺寸、权重或本地 runtime，当前产品仍是云 API。低价格和低延迟还不能证明它适合 edge。',
    '更长远看，Jev 带来的生态未必围绕某一家公司的 API。`state + typed questions → probabilities` 可能成为一种独立的模型接口。Agent runtime 与 memory，以及 eval、router 和安全系统都可以围绕这个接口组合不同模型。主流 LLM 厂商也可能直接增加 decision endpoint，把生成和判断做成两种调用方式。',
    '到那时，开发者积累的不只是 prompt。问题定义和候选项会成为系统资产，标注数据与校准曲线也会留下来，此外还有自动执行阈值和升级策略。模型可以更换，这套判断契约仍然留在程序里。',
    '## 我现在怎样看 Jev',
    'Jev 目前仍有不少空白。架构和 RLCD 没有技术论文，模型规模和训练成本未知，校准优势没有在所有独立对照中成立，公开应用大多还是 cookbook、模拟项目和小样本实验。',
    '不过它提出的问题很实际。我们已经习惯用 LLM 完成所有带语义的工作，其中不少调用最终只留下一个布尔值、一个类别或一个分数。让生成模型完成这些判断当然能用，只是系统同时承担了长输出和解析，加上延迟与更难控制的失败形态。',
    'Jev 给出的答案，是把这部分判断变成单独的模型调用。自己的业务能不能明确写出候选项、准备可靠的 state，并用真实结果验证概率和阈值，决定了 Jev 是否值得采用；发布页上的百倍数字不能替代这项判断。',
    '如果这些条件成立，Jev 可以成为 Agent 里一层很轻的判断能力。需要创造、规划和解释的部分继续交给 LLM，需要执行和权限保证的部分继续留给代码。这个分工比“再找一个更聪明的模型包办全部事情”更值得继续观察。',
    '## 参考资料',
    '- [Introducing System One Models & Jev](https://typesafe.ai/blog/introducing-system-one-models-and-jev)\n- [TypeSafe AI primer](https://docs.typesafe.ai/introduction/machine-learning-primer.md)\n- [Models and pricing](https://docs.typesafe.ai/models)\n- [Jev 1.13 known jaggedness](https://docs.typesafe.ai/model-jaggedness/jev-1.13)\n- [Jev calibration audit](https://github.com/jujumilk3/jev-calibration-audit/blob/main/FINDINGS.md)\n- [Jev Accuracy Tested](https://truestandard.ai/blog/jev-accuracy-tested)\n- [vinilana/jev-eval-agent](https://github.com/vinilana/jev-eval-agent)\n- [Jev as a judge for agent evals](https://github.com/danielgshea/jev-as-a-judge)',
  ],
  aiDisclosure:
    '本文由 AI 协助检索公开资料和核对引用，文章观点、结构与取舍来自作者对资料的理解和讨论。',
  readingMinutes: 14,
  category: 'software',
  topic: 'agent-architecture',
  featured: true,
  tags: ['Jev', 'LLM', 'Agent', 'Decision Model', 'RLCD'],
  status: 'published',
} satisfies BlogPost
