import type { BlogPost } from '../../data/types'

export const multicaLocalAgentWorkflow = {
  slug: 'multica-local-agent-workflow',
  title: 'Multica：把本地 AI Coding Agent 变成可管理的长任务',
  date: '2026-05-15',
  excerpt:
    '记录一下最近用 Multica 管理本地 AI Coding Agent 的体验：它更像一个让人当指挥官的任务协作层。',
  content: [
    '最近试了一下 Multica。它给我的第一印象不是又一个聊天窗口，而是一个把 AI Coding Agent 放进工作流里的协作层：你创建 issue，选择 agent，把任务交出去，然后在看板、运行记录和消息流里看它怎么推进、哪里卡住、最后交付了什么。',
    '## Multica 是什么',
    'Multica 的核心结构可以理解成三层：服务端负责 workspace、issue、task queue 和状态同步；本机 daemon 负责轮询任务、启动本地 AI coding tool；真正写代码的还是本地的 Claude Code、Codex、Cursor、Copilot CLI、Gemini 等工具。也就是说，它不是把你的代码和 key 丢给一个远端黑盒 runner，而是让本地机器成为 agent runtime。',
    '- Server：保存 workspace、issue、task queue、评论和状态。\n- Daemon：跑在自己的机器上，轮询任务并启动本地 coding agent。\n- AI coding tool：真正执行代码修改和验证，比如 Claude Code、Codex、Cursor、Copilot CLI、Gemini。',
    '## WSL 下的本地流程',
    '这个模型对我这种 WSL 用户比较舒服。我的代码、Node 环境、git、npm、Vite 项目都在 WSL 里，daemon 也可以跟着本地工具链一起跑。常见流程大概是先 setup，再确认登录状态，最后启动 daemon。',
    '```bash\n# 初次配置，登录并启动本地执行端\nmultica setup\n\n# 如果已经配置过，可以单独检查状态\nmultica auth status\nmultica daemon status\n\n# 启动、重启和查看 daemon 日志\nmultica daemon start\nmultica daemon restart\nmultica daemon logs\n```',
    '## 派任务和看交付',
    '真正开始派活时，CLI 也比较直接。可以先看 workspace 和 agent，再创建 issue，把 issue 分配给 agent。任务跑起来之后，用 runs 和 run-messages 看执行记录、消息、工具调用和错误。',
    '```bash\n# 看 workspace 和 agent\nmultica workspace list\nmultica agent list\nmultica agent create\n\n# 创建和分配任务\nmultica issue create --title "Polish About contact links"\nmultica issue list\nmultica issue assign <issue-id> --agent <agent-slug>\n\n# 查看交付和执行日志\nmultica issue runs <issue-id>\nmultica issue run-messages <task-id>\nmultica issue run-messages <task-id> --output json\n```',
    '## 用 issue 驱动一个长任务',
    '这类工具最适合的不是临时问答，而是把一个长任务拆成一组可以交付的 issue。我的使用方式更像是在 CLI 里写清楚任务、验收标准和优先级，然后让 agent 自己规划、修改、验证、回报。',
    '```bash\n# 用 issue 描述目标，而不是手动盯每一步\nmultica issue create --title "Build a personal website"\nmultica issue create --title "Polish the writing section"\nmultica issue create --title "Check responsive layout and production build"\n\n# 把任务交给本地 agent 执行\nmultica issue assign <issue-id> --agent <agent-slug>\n\n# 回看执行过程和交付信息\nmultica issue runs <issue-id>\nmultica issue run-messages <task-id>\n```',
    'Yuniverse 这个个人网站基本就是用这种方式推进出来的。我一边实习，一边在 CLI 里写 issue、补充目标和反馈，不需要一直盯着每一步具体怎么改。agent 会自己读代码、拆任务、调整页面、跑验证，再把交付信息汇报回来。',
    '这件事对效率的提升很明显。个人网站这种项目不是纯粹的一次性代码生成，而是会反复经历内容整理、页面调整、样式修正、构建验证和线上检查。如果每一步都手动盯，很容易被上下文切换拖慢；但用 Multica 之后，我更多是在关键节点判断方向、补充要求、验收结果。',
    '我自己的感觉是，我更像一个指挥官，而不是每一步都亲手敲代码的人。我需要描述目标、检查交付信息、判断方向是否对、在关键节点接管决策；agent 负责展开计划、读代码、改文件、跑验证、汇报结果。短时间内，一个长任务就能被规划成可执行的路径，而且每一步都有状态和日志可以回看。',
    '它好用的地方还在于“本地”。严格说，任务同步和看板仍然需要服务端，但核心执行发生在自己的机器上：本地仓库、本地 CLI、本地 API key、本地测试环境。对于个人项目或者还没准备完全云端托管的开发流，这种方式比纯云端 agent 更有安全感，也更接近我平时真实写代码的环境。',
    '当然，这类工具也不是魔法。issue 要写清楚，验收标准要具体，agent 的权限和工作目录要管好，最后的测试和线上验证也不能省。但作为一个把多个 coding agent 管起来的协作层，Multica 给我的感觉是：它把 vibe coding 从“开一个聊天窗口反复催”推进到“像安排队友一样安排任务”。这对长任务尤其有用。',
    '这篇先作为使用记录。后面如果继续用 Multica 跑更多任务，可以再单独写一篇，把 agent 配置、run messages、失败重试、日志分析和具体交付案例拆开讲。',
  ],
  aiDisclosure: '本文由 AI 协助整理表达，内容来自个人使用体验和 Multica 官方文档。',
  readingMinutes: 4,
  category: 'software',
  featured: true,
  tags: ['Multica', 'Agent', 'Vibe Coding', 'WSL'],
  status: 'published',
} satisfies BlogPost
