import type { BlogPost } from '../../data/types'

export const nanoNotebookDevLog01 = {
  slug: 'nano-notebook-dev-log-01',
  title: 'nano-notebook 开发日志 01：我为什么做一个自己的 NotebookLM',
  date: '2026-08-07',
  excerpt:
    '第一篇讲产品故事和整体技术选型：为什么拿 NotebookLM 当蓝本，为什么选择自托管，以及 Go/PostgreSQL/Qdrant 这套栈背后真正想解决什么问题。',
  content: [
    '这篇是 nano-notebook 开发日志的第一篇。后面会写 Agent Runtime、Checkpoint、Trace、工具调用、权限、RAG、并发这些具体机制，但第一篇先把两件事讲清楚：我为什么做它，以及我为什么选这套技术栈。',
    '## 为什么拿 NotebookLM 当蓝本',
    '我选择模仿 NotebookLM，不是因为想做一个一模一样的产品，而是因为它是一个很好的 Agent 学习对象。',
    'NotebookLM 不是某个垂直业务里的工具，而是一个通用学习工具。报告、闪卡、知识图谱、PPT 这类产出，几乎所有行业和岗位都需要。没有具体业务场景，意味着业务知识对产品形态的约束很少，我可以把主要复杂度放在 Agent Runtime 本身上：RAG、工具调用、权限、Trace、监控、多 Agent 协作，这些 Agent 开发里最常见的横切能力都能在这个产品里出现。',
    '这确实有一个代价。没有具体业务场景，就很难为 Agent 产出设计一个足够好的业务 rubric，也就难说让 Agent 根据结果自进化。但我判断，制作通用 Agent Runtime 本身就是必经之路。大公司做具体场景的 Agent 时，通常也不是每个业务都从零写一套 runtime，而是在一个成熟的通用 Agent Runtime 上做业务开发和配置。把这件事练一遍，比直接堆业务提示词更能训练 Agent 基础设施的能力。',
    '所以这个项目从一开始就定了一个原则：麻雀虽小，五脏俱全。规模可以小，但 Agent 系统真正难的那几条链路，必须真实存在。',
    '## 为什么不自用现成的，而是自己做一个',
    '另一个原因是 NotebookLM 是闭源的。',
    '越是对数据敏感的公司，越会希望有一份可以自己部署的 NotebookLM。公共 SaaS 在处理法律、金融、医疗、研发这类材料时，数据主权和合规边界很难被接受。自托管至少能回答“数据不出公司”这个问题。',
    '但“闭源”只是起点。更让我感兴趣的是，闭源产品也会拿走 Agent 开发里最关键的一层：反馈闭环。公共产品不会给你完整的 Trace、Replay、rubric 和 Eval，你很难知道 Agent 为什么答错，也很难验证改完以后有没有变好。自己做一个，才能把“可观测、可回放、可评测”做成基础设施的一部分，而不是等上线后靠用户报告问题。',
    '自托管还带来另外两个自由度：模型和供应商可以替换，不用被某个模型的 embedding、rerank、prompt 和输出格式锁死；功能边界也可以按自己的需求控制，比如对接内部权限、审批和现有知识系统。',
    '## 产品形状先定下来',
    '产品方向确定后，我先固定了产品形状，避免后面被“再加一个功能”带偏。',
    '- Notebook 是证据边界，用户围绕一个主题维护 Source，而不是有一个全局大知识库。\n- Source 是内容来源，可以上传文档、网页、视频、音频、图片，但必须处理成可引用的 Evidence。\n- Chat 是私有研究空间，围绕 Notebook 里的 Sources 提问，回答必须能回到原文证据。\n- 分享和权限采用 Viewer、Editor、Owner 三层，Sources 共享，但每个成员的 Chat 历史保持私有。\n- 产出从报告、闪卡、知识图谱这类学习形态逐步扩展。\n- 不把通用 Web Search、通用工作流引擎、任意 Agent 沙箱当成第一版目标。',
    '这个形状定下来之后，技术选型就不是“选最新最潮的”，而是选最配合这些约束的。',
    '## 技术选型：先想清楚谁是真源',
    'nano-notebook 的技术栈可以概括成一句话：PostgreSQL 和 S3 是真相来源，Qdrant 是可重建的检索投影，Go 负责 Agent Runtime 的状态机和并发，Bifrost 负责模型接入，React 只做前端展示。',
    '## Go：让 Agent Runtime 的状态机好写',
    '核心没有选 Python 或 Node，而是用 Go 做 Control Plane、Durable Runtime、Worker 协调、权限、Chat 和 RAG orchestration。',
    '这不是因为 Go 一定“更快”，而是因为 Agent Runtime 本质上是一个并发状态机。Agent Run、Job、Checkpoint、工具调用、权限检查，不是简单请求进来返回结果，而是多个 Worker 并发推进的长时间状态迁移。Go 的 goroutine、channel、显式并发模型和静态类型，比较适合把这种状态机写清楚。',
    '另一个原因是部署形态。同一个 Go 项目可以编译成静态二进制，按不同入口跑 Control Plane、Agent Worker、Source Worker 或 Eval CLI。这和 modular monolith 是配套的：一个 Go codebase，内部按 `agent`、`source`、`chat`、`retrieval`、`jobs` 等模块划分边界，模块之间通过内部接口协作，而不是一开始就拆成微服务。',
    '真正适合 Python 的部分，比如 OCR、转录、embedding、格式解析，也保留，但只能作为 Extractor Adapter 存在，不能拥有权限、Job 生命周期或权威业务状态。',
    '## PostgreSQL：一个能同时做事务、权限和 Job 的系统',
    '为什么用 PostgreSQL 而不用 MySQL，是这个项目里最值得讲清楚的一个选型。',
    'MySQL 当然能存关系数据，但 nano-notebook 最需要的几个能力，PostgreSQL 配合得更顺：\n- 所有关键状态可以放在同一个事务边界里：用户、Notebook 成员、Source、Chat、Agent Run、Job、Citation，要么一起提交，要么一起回滚。\n- Row-Level Security 可以在数据库层再挡一层，即使应用层查询写错，也很难跨 Notebook 或跨用户读到数据。\n- `LISTEN/NOTIFY` 可以低延迟唤醒 Worker，同时 Job row 仍然是唯一事实，不需要额外引入一套消息队列。',
    '所以更准确的说法不是“Postgres 吊打 MySQL”，而是：Postgres 让事务状态、权限隔离和 Job 唤醒尽量落在同一个系统里，MySQL 也能做，但需要更多应用层补丁。',
    '## S3/MinIO 与 Qdrant：不可变内容 vs 可重建检索',
    'Source 原始文件是大对象，而且是不可变证据，不应该塞进 PostgreSQL。S3 API 是 Blob Store 的契约：本地用 MinIO，生产用 AWS S3，上传走 presigned URL，字节不经过 Go 请求路径。',
    '向量检索则单独交给 Qdrant。Qdrant 不是真相来源，而是可重建的检索投影。它负责 dense、sparse、filtered 和多阶段检索，但只存向量和最小的检索元数据；真正权威的 Evidence 内容仍由 PostgreSQL 校验后加载。',
    '为什么不是 pgvector？pgvector 更省事，但会把检索和业务数据库耦合在一起，检索实验、版本、重建都挤在同一个系统里。为什么不是 Milvus？目标规模用不上它的分布式存储和计算拓扑，运维复杂度不划算。单节点 Qdrant 对这个产品刚刚好。',
    '## Bifrost 与 React：把边界留清楚',
    '模型接入通过独立 Bifrost Gateway 做协议归一化、bounded retry 和 provider fallback。Nano 自己保留 Agent 状态、路由意图、检索和恢复语义，不让 provider SDK 直接长在 Worker 里。',
    '前端是 React + TypeScript SPA，只消费 Go Control Plane 的 REST 和 SSE 接口，不做业务后端，也不维护第二套权限逻辑。',
    '## 这套栈不是终点，而是后面每一篇的地基',
    '现在回看，第一篇真正要记录的选型不是某个库好不好用，而是一条主线：谁拥有权威状态，谁拥有执行状态，谁只是可重建投影。',
    '- Agent Runtime 为什么会用 PostgreSQL 做 Job 和 Checkpoint\n- Trace 链路为什么不能只画 Span，还要能 Replay\n- RAG 为什么要把 Evidence Unit 和 Retrieval Chunk 分开\n- 工具调用为什么要把模型选择、权限、预算和恢复分开\n- 并发工具调用和 Agent 协作时，权威状态怎么避免被多个 Worker 打乱',
    '这也是我选择这个项目的原因：它不是一个 demo，而是一个能让我把 Agent 基础设施从产品边界一路做到源码实现的项目。',
    '仓库：[huangxinxinyu/nano-notebook](https://github.com/huangxinxinyu/nano-notebook)',
  ],
  aiDisclosure:
    '本文由 AI 协助整理表达，技术决策与实现来自 nano-notebook 项目的真实开发记录和仓库文档。',
  readingMinutes: 6,
  category: 'software',
  topic: 'agent-architecture',
  series: 'nano-notebook-dev-log',
  tags: ['nano-notebook', 'Agent Runtime', 'NotebookLM', '技术选型', 'RAG', 'Go'],
  status: 'published',
} satisfies BlogPost
