import type { BlogPost } from '../../data/types'

export const nanoNotebookDevLog06 = {
  slug: 'nano-notebook-dev-log-06',
  title: 'nano-notebook 开发日志 06：Prometheus + Grafana，让 Agent 项目从“跑通”变成“可运维”',
  date: '2026-08-07',
  excerpt:
    '第六篇讲 Prometheus + Grafana 在 Agent 项目里到底解决什么问题：任务成功率、分阶段延迟、typed error、泄漏 gauge 怎么埋，PromQL recording rule / alert rule 怎么组织，以及从单机扩展到分布式集群时要补哪些指标。',
  content: [
    '前面几篇把 Agent 怎么执行、怎么恢复、怎么调工具讲完了。这一篇把视角从“一次 Run”拉到“整个系统”：当 Agent 项目已经能跑通之后，运维要回答的已经不是某个 Trace 里发生了什么，而是过去一小时系统整体是不是健康、哪里在变慢、失败集中在哪个原因、Worker 的内存是不是在悄悄涨。',
    '我的核心结论是：Trace 回答“这一次 Run 到底发生了什么”，Prometheus + Grafana 回答“整个系统现在是什么状态”。两者不是替代关系，而是两套不同粒度、不同保留周期、不同查询方式的可观测面。Agent 项目尤其需要 metrics plane，因为一次 Agent Run 不是一次普通 HTTP 请求，它跨队列、Worker、模型、工具、检索和发布多个阶段，只靠日志或单个 Trace 很难发现系统性回归。',
    '## 为什么需要 Prometheus + Grafana',
    'nano-notebook 在加这套东西之前，已经有很强的 per-run 观测能力：Durable Trace、Collector、Replay、Jaeger。它能精确回答“这个 Run 为什么慢、哪一步失败、这个模型调用花了多少 token”，但回答不了四个很常见的运维问题：',
    '- 过去一小时，Chat 任务成功率是多少？\n- p99 变慢了，慢在 queue wait、model call、tool execution 还是 retrieval？\n- 失败率升高，是模型不可用、工具报错、权限丢失还是 deadline 过期？\n- Worker 长期运行后，内存和 goroutine 是不是在涨，会不会某天 OOM？',
    'PostgreSQL 里有 `agent_runs.status` 这类终端状态，但没有时间序列；模型调用和检索里已经有耗时，但没有聚合；`ClassifyAttempt` 已经给每次失败分好类，但分类结果用完就丢；SSE subscriber、heartbeat goroutine、pgx pool 这些长期存活的内存结构也没有暴露出来。这些问题不是缺日志，而是缺一个聚合的、低基数的、带时间的指标面。',
    'Prometheus 解决的是采集和查询：服务暴露 `/metrics`，Prometheus 按固定间隔拉取，按 label 聚合，histogram 支持 p50/p95/p99，recording rule 把“成功率怎么算”定义一次，alert rule 在指标越过阈值后触发。Grafana 解决的是把同一套指标变成可阅读、可分享、可复现的 dashboard，而且 dashboard 应该用 provisioning 文件维护，不是每次手工拖面板。',
    '## 这类工具平时用在什么任务上',
    '在传统后端里，Prometheus + Grafana 最常见的用途已经足够明确：',
    '- RED：Rate、Errors、Duration，看接口流量、错误率和延迟。\n- USE：Utilization、Saturation、Errors，看 CPU、内存、连接池、队列占用。\n- SLO：用 recording rule 定义成功率/错误预算，再用 multi-window burn rate 告警，避免一个瞬时抖动就打爆手机。\n- 容量和回归：看某个服务、某个依赖、某个版本的指标变化，判断是代码回归、流量增长还是外部 Provider 抖动。',
    'Agent 项目里这些用途全都保留，但还要再加四类 Agent 特有的任务。',
    '第一，Agent Run 是 durable task，不是 request/response。一个消息提交后要经过 admission、queue、worker claim、model decision、tool call、publication，最后才成为正式答案。只看 HTTP 延迟会漏掉任务排队、重试和最终结果，所以必须按 Task 生命周期统计从 admission 到 terminal 的 end-to-end 指标。',
    '第二，Agent 失败不完全等于 HTTP 500。很多失败是“系统没有崩溃，但任务没有按预期完成”：deadline 超时、retry 耗尽、lease 丢失、检索降级但答案仍然发布。成功率、attempt 次数和 typed error code 比单纯看 5xx 更接近真实健康度。',
    '第三，Agent 天然包含重试和恢复。同一次 Run 可能被不同 Worker claim，同一个 Action 可能因为不确定 ACK 被重复执行。只看“最终成功/失败”会隐藏重试放大和 Lease 异常，所以 `nano_agent_attempt_total` 和 `nano_agent_run_attempts` 这类指标很重要。',
    '第四，Agent 服务有大量长生命周期内存结构。SSE hub、per-claim heartbeat goroutine、inflight attempt、Collector 队列、pgx pool，都可能泄漏。这类问题不能等到 OOM 再发现，必须用 gauge 暴露 steady state，并且配合 Go 的 live heap / goroutine 指标做持续监控。',
    '## 哪些指标是我们最关心的',
    '指标不用面面俱到。nano-notebook 的 Sprint 12 把核心指标收敛成四组。',
    '## 任务成功率',
    '`nano_task_terminal_total{task_kind,task_variant,outcome}` 是任务生命周期的地基。每个任务只在进入 terminal state 时记一次，`outcome` 只有 `completed`、`failed`、`cancelled`、`expired` 四种。',
    '这里有两个容易做错的语义：',
    '- `cancelled` 不进成功分母。用户主动停止不是系统缺陷，把取消算进去会让成功率跟着用户行为波动。\n- `expired` 要算失败。deadline 超时是系统没在承诺时间内完成，不是用户主动取消。',
    '成功率不能散落在 dashboard 和 alert 里各写一遍，而是在 recording rule 里定义一次。比如：',
    '```promql\nsum by (task_kind, task_variant) (rate(nano_task_terminal_total{outcome="completed"}[5m]))\n/\nsum by (task_kind, task_variant) (rate(nano_task_terminal_total{outcome=~"completed|failed|expired"}[5m]))\n```',
    '所有面板和告警都消费这个 recording rule，后续改成功率口径时只改一处。',
    '## 分阶段延迟',
    '普通接口延迟通常只需要一个 histogram。Agent 任务必须拆阶段，否则看到一个慢 Run 时还是不知道慢在哪里。',
    'nano-notebook 用这些 histogram：',
    '```text\nnano_task_queue_wait_seconds     available_at -> Worker claim\nnano_chat_first_progress_seconds SSE subscribe -> 第一条进度事件\nnano_model_call_seconds          单次模型 round trip\nnano_tool_execution_seconds      MCP tool plane 边界\nnano_retrieval_stage_seconds     dense / bm25 / fuse / evidence_load / rerank\nnano_retrieval_search_seconds    整次 Pipeline.Search\nnano_task_end_to_end_seconds     admission -> terminal\n```',
    '所有延迟都用 Histogram，不用 Summary。原因很实际：Summary 的 quantile 不能跨多实例聚合，分布式后每个实例单独算分位，全局 p95 就没有意义；Histogram 的 `_bucket` 可以按 label 做 `sum by (le)` 再算 `histogram_quantile`。',
    '延迟告警也只盯 p95/p99，不盯平均值。平均值会被大量快请求拉平，一个慢尾可能藏在里面。',
    '还有一个 Agent 项目特有指标：unattributed time。end-to-end 减去已经归因的 queue、model、tool、retrieval 后，剩下的 gap 单独画出来。如果这个 gap 持续变大，通常不是系统变快，而是某个新阶段忘了埋点。这个指标专门抓“没有 instrumentation 的时间”，而不是假装时间消失了。',
    '## 错误原因',
    '`nano_error_total{task_kind,layer,error_code}` 不是简单数 5xx，而是复用已有的错误分类。Agent 运行时本来就有 `ClassifyAttempt`，它会区分 retryable 和 terminal，并产出稳定 error code；Prometheus 指标直接把这次分类结果接出来。',
    '这样排查顺序是：先看错误率按 `layer` 上升，再看是 `model`、`tool`、`retrieval`、`storage`、`authorization`、`contract`、`budget` 还是 `lifecycle`；然后看具体 `error_code`，比如 `model_unavailable`、`tool_not_allowed`、`lease_lost`、`run_deadline_exceeded`。这比“错误数上升了”更有操作性。',
    'HTTP 和 SSE 也要分开：',
    '- 普通 API 用 `nano_http_requests_total` 和 `nano_http_request_duration_seconds`，route 只记路由模板，比如 `/api/v1/notebooks/{id}/studio-outputs`，不记实际请求路径。\n- SSE 长连接不能放进普通 HTTP duration histogram，否则一个多小时的长连接会毁掉整条接口延迟分布。SSE 单独用 `nano_sse_connections_active`、`nano_sse_connection_duration_seconds`、`nano_sse_events_sent_total`。',
    '## 运行时与泄漏',
    'Agent 服务的长期运行特性决定了必须监控 Go runtime。',
    '泄漏告警不要直接盯 RSS 或 `go_memstats_heap_inuse_bytes`。RSS 和 heap inuse 反映的是 allocator 保留和 GC 调度，不一定是真实泄漏。nano-notebook 用 `go_gc_heap_live_bytes`，也就是 GC 完成后的 live heap，再叠加一个持续增长条件：',
    '```promql\n(go_gc_heap_live_bytes / (go_gc_heap_live_bytes offset 6h)) > 1.5\nand (time() - process_start_time_seconds) > 21600\n```',
    '第二条要求进程已经运行超过 6 小时，否则一次 restart 也可能被误判成泄漏。',
    '光有 live heap 还不够，还要有应用级 gauge 来定位泄漏面：',
    '- `nano_runhub_subscribers`：SSE subscriber 数量。\n- `nano_worker_inflight_attempts`：正在执行的 attempt goroutine。\n- `nano_worker_heartbeat_goroutines`：lease heartbeat goroutine。\n- `nano_sse_connections_active`：当前打开的 SSE 连接。\n- `nano_db_pool_connections`：pgx pool 的 acquired/idle/total/max。',
    '其中 subscriber、inflight attempt、heartbeat goroutine 和 SSE 连接这类泄漏面的 steady state 是 0；DB pool 不是归零，而是看 `acquired / max` 的占用比例。如果 live heap 涨的同时某个应用 gauge 也在涨，泄漏面基本直接定位；如果所有相关 gauge 都正常，再上 `/debug/pprof/heap` 做前后两次 diff。',
    '## 怎么得到这些指标',
    '指标不是把 Prometheus 客户端到处 `Inc()` 就完了。nano-notebook 的做法是先定一个共享的 `internal/platform/metrics` 包，把所有指标集中注册。',
    '每个服务只暴露一个专用 admin listener，默认是 control-plane `:9091`、worker `:9092`、collector `:9093`、fetcher `:9094`、document-renderer `:9095`。这个 listener 只提供 `/metrics` 和 `/debug/pprof/*`，不挂在公共 API mux 上，也不通过 nginx 暴露；在 Compose 里也不映射到宿主机端口，只有 Docker 网络内部能访问。',
    '指标注册时有几道硬约束：',
    '- 所有应用指标必须有 `nano_` 前缀，并且名字以 `_seconds`、`_bytes`、`_total` 等基础单位结尾。\n- 重复注册或命名不合法会让进程启动失败，而不是上线后才发现少数据。\n- label 只允许来自 closed allowlist。任何 open-ended 的 label 值，比如 error message、query text、Run ID、用户 ID，都不能进 Prometheus label；不知道的新值先变成 `other`，同时增加 `nano_metrics_label_rejected_total` 报警，提醒这是 instrumentation defect。\n- 有 cardinality budget 测试，把每个 metric 的 label 域相乘，保证单实例 series 数量在预算内。',
    '埋点位置也是刻意选的：',
    '- Task terminal 在终端事务 commit 后记一次，和 Trace publish 用同一个 after-commit 模式。\n- Queue wait 在 `ClaimNext` claim 到 Job 时测，不需要新增请求。\n- Model call 复用 `ModelOutcome.Metadata.Latency`，不加第二套计时。\n- Tool execution 在 MCP `CallTool` 边界测，保证所有执行路径都经过 MCP。\n- Retrieval stage 直接读 `SearchDiagnostics` 已有的五个阶段耗时。\n- HTTP/SSE 在 middleware/stream scope 里测。\n- Worker 和 run hub 在 goroutine 创建/退出时维护 gauge。',
    'Prometheus 侧用 15s scrape interval、15d retention，recording rule 和 alert rule 都作为文件提交。Grafana 通过 provisioning 配置 datasource 和 dashboard，dashboard 文件是 `sprint-12-operations.json`，里面包含成功率、错误预算 burn rate、分阶段延迟、unattributed time、error layer/code、泄漏 gauge、live heap/goroutine、DB pool、HTTP route 这些面板。',
    '告警也有 runbook，而且告警表达式的组织方式本身很重要：',
    '- availability 用 multi-window burn rate，不是瞬时错误率阈值。\n- latency 用 30m 的 p95/p99 recording rule。\n- leak 用 live heap 持续增长 + process uptime。\n- 每个 alert 都带 runbook 链接，告警不是只发一个“指标高了”。',
    '## 扩展到分布式项目时怎么改',
    'nano-notebook 当前是单机 Compose + 有限服务数，Prometheus 用 static config 就够了。真正分布式后，指标采集和告警的骨架不用推翻，但要补四件事。',
    '第一是 target discovery。static config 会变成 file_sd、DNS discovery、Consul、Kubernetes 这类 service discovery。`job`、`instance` 这类 target label 应该由 Prometheus relabel 阶段加，应用指标里不要自己带 `service`、`instance`、`pod`、`version` label。这样换部署平台时应用代码不用改。',
    '第二是聚合方式。单实例 p95 不能代表全局 p95；分布式后应该继续用 Histogram，把多个实例的 `_bucket` 按 `le` 先 sum，再算 `histogram_quantile`。所有延迟指标在设计时就不能用 Summary，这条在单机时看起来无所谓，分布式时是硬约束。',
    '第三是 alert scope。成功率、错误预算这类全局 SLO 要按 service/scope 聚合后判断；实例级别的 p95 抖动可能只是单台机器问题，不该触发全局 page。可以保留“实例级 ticket”和“服务级 page”两层告警，而不是所有告警都按单个 instance 写。',
    '第四是补新指标。单机 Agent 项目最关心 Run 是否完成，分布式后要额外关心调度和依赖：',
    '```text\nqueue_depth / queue_lag_by_kind\nworker_claim_rate / inflight_by_worker\nlease_expired_total / lease_reclaim_total\nmodel_provider_rate / model_error_rate / model_latency_by_model\nexternal_dependency_availability\ntrace_pipeline_ingest_lag / dropped_batches / retry_total\ninstance_restart_total / runtime_heap_by_instance\ntask_success_by_definition_and_model_version\n```',
    '其中很多指标不是新发明，而是把单机里已经有的 gauge/histogram 加上 instance、model、provider 等有限维度，并保持 allowlist。真正要避免的是把 pod name、request ID、tenant ID 放进 label，因为基数会立刻失控；需要定位到具体实例的问题应该从 Trace 或 log 查询，不是用指标 label 硬扛。',
    '分布式也不改变两条边界：',
    '- 指标只回答 aggregate：多少个、多快、多少错误、是不是在泄漏。\n- 具体某个 Run 为什么失败，还是要回到 Trace/Replay。',
    '## 我们刻意没有做什么',
    '这篇没有把“日志、指标、Trace 全部塞进一个系统”。Sprint 12 的边界很清楚：不接 log pipeline、不做 per-user/per-notebook/per-run 指标、不做 answer quality dashboard、不做 token/cost dashboard。前三个是数据基数和语义问题，最后一个是独立产品问题，不该混进运维指标里。',
    '另外，指标当前只覆盖已经真正接线的核心路径。仓库 acceptance 里也记录了已知 gap，比如 run-level degraded success 关联还没完全接线、first-progress 当前测的是 SSE connect-to-first-byte。写这篇时我把“已实现的指标”和“设计里应该有的指标”分开了，不希望博客比仓库状态更乐观。',
    '## 源码锚点',
    '- [internal/platform/metrics/catalog.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/platform/metrics/catalog.go)\n- [internal/platform/metrics/registry.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/platform/metrics/registry.go)\n- [internal/platform/metrics/allowlists.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/platform/metrics/allowlists.go)\n- [internal/platform/metrics/server.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/platform/metrics/server.go)\n- [internal/agent/task_metrics.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/task_metrics.go)\n- [internal/app/http_metrics.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/app/http_metrics.go)\n- [internal/app/sse_metrics.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/app/sse_metrics.go)\n- [internal/worker/service.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/worker/service.go)\n- [internal/jobs/queue.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/jobs/queue.go)\n- [internal/agent/mcp_tool_plane.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/mcp_tool_plane.go)\n- [internal/agent/evidence_search.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/evidence_search.go)\n- [infra/observability/prometheus/prometheus.dev.yml](https://github.com/huangxinxinyu/nano-notebook/blob/main/infra/observability/prometheus/prometheus.dev.yml)\n- [infra/observability/prometheus/rules/recording_rules.yml](https://github.com/huangxinxinyu/nano-notebook/blob/main/infra/observability/prometheus/rules/recording_rules.yml)\n- [infra/observability/prometheus/rules/alert_rules.yml](https://github.com/huangxinxinyu/nano-notebook/blob/main/infra/observability/prometheus/rules/alert_rules.yml)\n- [infra/observability/grafana/dashboards/sprint-12-operations.json](https://github.com/huangxinxinyu/nano-notebook/blob/main/infra/observability/grafana/dashboards/sprint-12-operations.json)\n- [docs/sprint/SPRINT-12-PRD.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/sprint/SPRINT-12-PRD.md)\n- [docs/sprint/SPRINT-12-ACCEPTANCE.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/sprint/SPRINT-12-ACCEPTANCE.md)\n- [docs/engineering/BACKEND_ENGINEERING.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/engineering/BACKEND_ENGINEERING.md)',
  ],
  aiDisclosure:
    '本文由 AI 协助整理表达，技术决策、实现与指标来自 nano-notebook 仓库的 Sprint 12 实现、PRD、alert runbook 和 acceptance 文档。',
  readingMinutes: 10,
  category: 'software',
  topic: 'agent-architecture',
  series: 'nano-notebook-dev-log',
  tags: ['nano-notebook', 'Prometheus', 'Grafana', 'Observability', 'Metrics', 'Alerting', 'Go'],
  status: 'published',
} satisfies BlogPost
