import type { BlogPost } from '../../data/types'

export const nanoNotebookDevLog04 = {
  slug: 'nano-notebook-dev-log-04',
  title: 'nano-notebook 开发日志 04：RAG 全流程、混合检索与离线评测',
  date: '2026-08-07',
  excerpt:
    '第四篇把 RAG 从“向量搜索”拆成一条可评测的工程链路：Evidence Unit 与 Retrieval Chunk 分离、Dense + BM25、RRF、rerank 阈值，以及先拿引用、筛选完再进模型上下文的数据量控制。',
  content: [
    '为什么要用 RAG？最直接的原因是：通用模型记不住，也不该记住用户自己的资料。',
    'nano-notebook 要回答的不是“世界知识”，而是用户放进 Notebook 的私有 Source：本地文档、网页、PDF、表格、PPT、音视频转录。这些内容模型没有训练过，直接问模型，它只能靠常识补，既不可靠，也没法保证 citation。Fine-tuning 也不是答案：训练慢、成本高、更新一次资料就要重新动模型权重，而且它改变的是模型记忆，不是可验证的证据边界。',
    '把所有 Source 一次性塞进上下文也不行。Notebook 里可能同时有几十个文档，每个文档又切成大量 chunk，全部塞进去，token、延迟、成本都不可控；上下文越大，模型反而越难定位真正回答问题的片段，长文档末尾的信息很容易被稀释。',
    'RAG 把这个问题拆成两步：先把 Source 变成可检索、可引用的 Evidence 索引，再根据问题只取出相关引用和 bounded 正文进入模型上下文。它换来三件事：上下文规模可控、知识更新只改索引不改模型、回答可以回到原文验证。',
    '所以 nano-notebook 从第一天就把 RAG 当成基础设施，而不是一个“搜一下再回答”的可选工具。它最难的部分也不是写检索，而是让每一层都有明确边界，并且能离线回答“这个参数为什么这么定”。',
    '## RAG 的第一问：谁是真源，谁是投影',
    'nano-notebook 的第一条原则是：PostgreSQL 和 S3 是真相来源，Qdrant 只是可重建的检索投影。',
    'Source 原始文件进入对象存储，Normalizer 把它变成结构化的 Normalized Source。Evidence Publisher 再把它切成稳定的 Evidence Unit。Unit 是引用地址，比如一个文档段落、表格、PDF 页面区域、PPT 元素、图片区域或音视频片段，Citation 最终只指向 Unit 和 rune 区间，不指向 Qdrant 点。',
    'Qdrant 里存的是 Retrieval Chunk。Chunk 由 Evidence Unit 按版本化规则构建，当前配置是最大 800 runes、重叠 120 runes、尽量保留 heading 上下文。每个 Qdrant point 只保留 chunk 身份、索引版本、dense vector、BM25 sparse vector 和覆盖到的 Unit IDs，不存完整权威文本。查询命中后，再从 PostgreSQL 重建 candidate，所以换 chunk 策略、重 embedding、甚至整个索引重建，都不会破坏历史 Citation。',
    '这也是 ADR 0019、ADR 0020 的核心：向量库负责召回，PostgreSQL 负责证据。',
    '## 为什么用 Qdrant：和其他向量库怎么比',
    '选向量库不是选“谁速度快”，而是先选“它在我架构里承担什么角色”。nano-notebook 明确只让它当 retrieval projection，所以比较时最看重四件事：能不能把检索实验和业务数据库分开、能不能同时跑 dense 和 BM25、能不能做按 Notebook/Source/Index Version 的服务端过滤、以及本地和单机部署是否够轻。',
    '先看 pgvector。它的最大优势是省一个组件，向量直接和业务数据放在同一个 PostgreSQL，事务、权限、备份都天然复用。但这也正是它的问题：检索索引、chunk 重建、embedding 模型迁移、rerank 实验会全部挤进业务数据库。nano-notebook 需要经常把 candidate index、active index 同时保留，还要全量重建再 promote，把这件事放在业务库会放大迁移和运维风险。pgvector 适合“检索规模不大、不想多养一个服务”的项目，不适合“检索层要反复实验和整体重建”的项目。',
    '再看 Milvus。它是很完整的分布式向量系统，适合大语料、大并发、需要分布式存储和计算拓扑的场景。但 nano-notebook 的目标是个人 Notebook 和中小团队，单机 Qdrant 已经能覆盖 dense、sparse、filter 和多阶段检索。为了还没出现的规模，先背上 Milvus 的组件、运维和部署成本，不符合这个阶段的需要。ADR 0008 的结论也是：先单节点，等有测量到的扩容需求再谈集群。',
    'Elasticsearch 或 OpenSearch 是另一个容易想到的选项，因为它们天然同时支持 BM25 和向量检索。但我们的架构里 PostgreSQL 已经是权威业务库，再引入一个通用搜索引擎，等于同时维护两套文档模型、两套索引语义和两套权限边界。Qdrant 只做窄的检索投影，角色更清晰，也更容易整个重建。',
    'Pinecone 这类托管向量库解决的是“不想自己运维”的问题，适合直接接受云厂商托管和对应成本。nano-notebook 的目标是自托管和本地可跑，所以更倾向能放进 Docker Compose、能本地启动、也能部署到自己的单台服务器上的方案。',
    '最后落到 Qdrant：它给了我们一个独立的检索表面，dense vector 和 sparse vector 存在同一个 point 上，`notebook_id`、`source_id`、`revision_id`、`index_version_id` 可以做 indexed payload filter，查询 scope 由服务端构造，客户端不能传任意过滤条件。Qdrant 数据丢了，结果是“检索投影不可用，需要重建”，而不是“证据丢了”。这就是我们想要的边界：检索基础设施可以坏、可以换、可以推倒重建，但不能影响权威内容。',
    '## BM25：为什么保留一套经典 lexical 通道',
    '我们不是“只做 dense”。生产检索同时跑 dense 和 BM25，原因很实际：embedding 对语义近似强，但 exact term、代码标识符、编号、表格字段、人名地名这些场景，lexical 往往更可靠；混合检索还能在两路各自失败时互相兜底。',
    'BM25 的实现在 `internal/retrieval/bm25.go`、`sparse_encoder.go` 和 `analyzer.go`。注意一个细节：生产不是每次查询都扫描内存文档算 BM25，而是在索引构建时用相同的 analyzer 和 BM25 参数把 chunk 编码成 sparse vector 存进 Qdrant，查询时用同一个 encoder 生成 query sparse vector，再由 Qdrant sparse search 完成召回。',
    '```text\nanalyzer: nano-mixed-v1\nk1: 1.2\nb: 0.75\naverage document length: 240\n```',
    '`nano-mixed-v1` 对英文单词和数字做小写化，对中文按单字和相邻 bigram 切分。Document 侧的 sparse weight 是经典 BM25 TF 饱和项，Query 侧主要表达 term 出现。Term 的 sparse index 由 `analyzer ID + term` 做确定性 hash 得到，避免两套词表在 build 和 query 时不一致。Qdrant collection 里 sparse vector 使用 IDF modifier，客户端会校验 collection 配置，防止索引侧和查询侧语义漂移。learned sparse embedding 目前刻意没上，因为 ADR 0019 要求先证明稳定 recall 差距，再决定要不要为它增加复杂度。',
    '## 一条完整的 RAG 链路',
    '离线侧：',
    '```text\nSource upload\n  -> normalizing\n  -> Evidence Units\n  -> Retrieval Chunks\n  -> dense embedding + sparse BM25 encoding\n  -> Qdrant upsert + verify\n  -> Source ready\n```',
    '在线侧：',
    '```text\n用户选择 Sources，Run 固定 evidence set 和 active Index Version\n  -> 查询 contextualization\n  -> dense embedding + sparse encoding（并发）\n  -> Dense 40 + BM25 40\n  -> RRF 融合\n  -> 截断到 rerank 候选\n  -> 从 PostgreSQL 重建权威 candidate\n  -> cross-encoder rerank\n  -> rerank relevance threshold 过滤\n  -> 最多 8 个 chunk 进入模型投影\n  -> grounded draft\n  -> grounding + publication barrier\n  -> 带 citation 的正式答案\n```',
    '## 召回量太大：先拿引用，筛选完再进模型上下文',
    '生产里最容易出现的效率问题是：Notebook 里有几十个 Source，每个 Source 又切成很多 800 rune 的 chunk，一个 query 如果直接把所有召回正文塞给模型，context 会爆炸，cross-encoder 也会贵到不可用。',
    'nano-notebook 的做法是让“引用”和“正文”分层流动，正文不随第一次召回结果直接进模型。',
    '```text\nQdrant 召回\n  -> 只返回 chunk_id + score + scope 元数据\n  -> RRF 融合，截断到 rerank 候选\n  -> 只为幸存 candidate 从 PostgreSQL 加载正文\n  -> rerank 排序 + threshold 过滤\n  -> 只有幸存 preview 进入模型上下文\n  -> grounding/publication 再回权威库校验引用\n```',
    '也就是说，Qdrant 返回的是“这篇可能相关”的引用，不是正文。经过 RRF 后，候选从最多 80 个收敛到 rerank 预算；只有这一小批才值得花跨编码器成本去读正文。rerank 后再按相关性阈值过滤，真正进模型上下文的通常远小于召回量。',
    '模型看到的 `search_evidence` 结果也不是完整 chunk。投影逻辑只保留 Source 信息、title 和 bounded preview，并且整个 action result 限制在 8 KiB JSON。放不下时先截 preview，再按顺序丢弃候选，同时显式标出 `truncated` 和 `omitted_count`，不会偷偷塞超长内容。',
    '最终答案的 citation 再回到 Unit 层。模型只需要拿到 bounded preview，发布时 grounding 会重新从 `source_evidence_units` 加载权威内容并校验引用，Qdrant chunk ID 永远不是 citation 身份。这样检索量、模型 context、成本、权限校验、可恢复性和引用稳定性被拆成了不同问题。',
    '## 我们的评测数据',
    '评测数据有两层。',
    '第一层是产品级 eval suite：跑完整 Agent loop，覆盖多格式、多语言和多模态场景，检查 expected evidence、required facts、forbidden facts、citation 正确性和 grounding 不变式。它作为 retrieval index promotion gate，candidate 没有 passing eval run 不能变成 active。',
    '第二层是检索层 sweep 数据集。它不跑 LLM，只复用生产 `EvidenceSearchService` 和 `retrieval.Pipeline`。当前 runbook 里是：',
    '- MS MARCO Passage 英文通用搜索 case\n- FiQA 英文金融域 case\n- DuReader-retrieval 中文通用搜索 case\n- CmedqaRetrieval 中文医疗域 case\n- 每个子数据集额外配随机 distractor Source',
    '`prepare_dataset.py` 只生成样本 JSONL，原始数据集文本不 commit，runbook 记录了各数据集来源和学术/非商业限制。`build-suite` 会把每个官方相关 passage 解析成 nano-notebook 自己的 Evidence Unit IDs，所以 ground truth 不是 dataset 的 passage ID，而是产品索引下的真实 evidence identity。',
    '## top_k / RRF / rerank 阈值怎么选',
    '选择方法不是拍脑袋，而是做参数网格。sweep grid 默认是：',
    '```text\ndense_candidates: 20, 40, 80\nsparse_candidates: 20, 40, 80\nrrf_k: 30, 60, 100\nrerank_candidates: 10, 20, 40\n```',
    '81 个组合，围绕生产基线 `40 / 40 / 60 / 20`。每个组合对每个 case 跑一遍真实检索，输出 Recall、MRR、每阶段耗时和失败数。',
    '第一次跑出来的 Recall 1.000 和 MRR 0.9825 看起来很好，但它不能用来选参数：每个 query 只有一个相关 passage，没有 distractor，评测集太容易，任何组合都能赢。top_k 和 RRF 的差异必须用更难的数据暴露出来，所以我后来把垂直域数据和随机 distractor 加进了评测集。',
    '生产基线 `40/40/60/20` 目前是网格的中心值，但真正的 top_k/rrf 终选要看更大语料、更多相关 passage 和真实成本曲线。rerank 候选预算和生产模型上下文预算也要分开看：检索层配置允许 `rerank_candidates=20`，正常 Agent 路径还会被 `maxSearchEvidenceCandidates=8` 截断，所以在线 `search_evidence` 最多只 rerank 8 个 chunk；离线 sweep 会关闭这个 cap，才能单独验证 20 是不是比 10 或 40 更值得。',
    'RRF 本身公式很简单：',
    '```text\nscore(id) = Σ 1 / (k + rank + 1)\n```',
    'rank 从 0 开始，`k` 越大，越往后的 rank 贡献越接近；`k` 越小，越看重每路的 top。它不比较 dense 和 BM25 的原始 score，只消费 rank，所以不需要跨模型归一化 score scale。nano-notebook 还要求每个 channel 内部不能有重复 candidate，并用 deterministic ID 处理同分，保证同 query 同索引结果是可复现的。',
    'rerank 阈值则必须用真实 score 分布来标定。扩展 suite 里只统计真正拿到 rerank 的 case：relevant candidate 的 p50 是 0.920，其他 candidate 的 p50 是 0.203，非 relevant 的 p75 恰好是 0.280。最初选 0.25，低于 relevant 最小值 0.261；但检查那个 0.261 的 case 后发现，它是 MS MARCO 里一个 passage 文本本身没提到问题实体、只靠标注者背景知识才判定相关的弱证据。于是最终阈值改成 0.28：会丢掉这一个弱 case，但能再过滤掉 [0.25, 0.28) 的 208 个低相关 candidate。',
    '这个阈值绑定 `cohere/rerank-v4.0-pro` 的 score scale，不是通用常数。换 reranker 必须重跑 score distribution。另外，rerank 失败时 pipeline 明确降级为 RRF 顺序并跳过阈值过滤，不会因为 reranker 挂了把所有结果都判成 irrelevant。',
    '## 离线评测怎么做',
    'nano-notebook 把离线评测拆成两条不互相污染的链路。',
    '产品级 eval 跑完整 Agent 执行，用来 gate retrieval Index Version promotion。`version_store.go` 里 candidate 必须先有一个 passed eval run，并且所有 active Evidence Revision 都完成 verified index build，才能 promote 成 active。这是“检索版本不能只靠代码 review 上线”的强制门禁。',
    '检索层 sweep 只评测 retrieval，不生成答案。`internal/rageval/retrieval_eval.go` 定义 RetrievalCase、RetrievalGrid、RetrievalReport，输出每个组合的 Recall/MRR 和 dense/BM25/fuse/evidence_load/rerank/total 每阶段耗时。每个 case 用 `SearchEvidenceWithOverrides` 复用生产代码路径，只是允许把 `rerank_candidates` 提升到配置值，而不是被模型上下文预算 cap 成 8。',
    '跑 sweep 时还有两个真实工程坑：查询 embedding 要按 case 缓存，否则 81 x 100 会产生 8100 次 embedding 调用；每次搜索前要同时刷新 Job lease 和 Run deadline，否则长 sweep 会在中途丢失 authority。',
    '## 当前结论',
    '现在能确认的是：dense + BM25 + RRF + rerank + relevance threshold 的机制已经端到端验证；阈值 0.28 有真实 score distribution；产品 eval gate 有冻结 suite 和硬阈值。参数选择会随 embedding、reranker 和语料变化，所以这些值不是一次性结论，而是以后每次换模型或扩大语料都要重新跑的部分。',
    '这也是我写这篇日志的原因：RAG 的工程问题不是“选一个向量库”，而是每一步都能说出为什么、用什么数据验证、参数变化会带来什么代价。',
    '## 源码锚点',
    '- [internal/retrieval/pipeline.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/retrieval/pipeline.go)\n- [internal/retrieval/bm25.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/retrieval/bm25.go)\n- [internal/retrieval/sparse_encoder.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/retrieval/sparse_encoder.go)\n- [internal/retrieval/rrf.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/retrieval/rrf.go)\n- [internal/retrieval/chunker.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/retrieval/chunker.go)\n- [internal/agent/evidence_search.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/evidence_search.go)\n- [internal/agent/search_evidence_projection.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/search_evidence_projection.go)\n- [internal/rageval/retrieval_eval.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/rageval/retrieval_eval.go)\n- [internal/qdrantstore/client.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/qdrantstore/client.go)\n- [internal/sourceprojection/projection.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/sourceprojection/projection.go)\n- [evals/rag/pinned-config-v1.json](https://github.com/huangxinxinyu/nano-notebook/blob/main/evals/rag/pinned-config-v1.json)\n- [docs/superpowers/specs/2026-08-03-rag-retrieval-sweep-design.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/superpowers/specs/2026-08-03-rag-retrieval-sweep-design.md)\n- [docs/superpowers/specs/2026-08-05-rerank-relevance-gate-design.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/superpowers/specs/2026-08-05-rerank-relevance-gate-design.md)',
  ],
  aiDisclosure:
    '本文由 AI 协助整理表达，技术决策、参数和评测结果来自 nano-notebook 仓库源码、ADR、eval suite 与 runbook。',
  readingMinutes: 11,
  category: 'software',
  topic: 'agent-architecture',
  series: 'nano-notebook-dev-log',
  tags: ['nano-notebook', 'RAG', 'BM25', 'RRF', 'Rerank', '离线评测', 'Qdrant'],
  status: 'published',
} satisfies BlogPost
