import type { BlogPost } from '../../data/types'

export const nanoNotebookDevLog03 = {
  slug: 'nano-notebook-dev-log-03',
  title: 'nano-notebook 开发日志 03：Trace 链路建模、Observability SDK 与 Dashboard 设计',
  date: '2026-08-07',
  excerpt:
    'nano-notebook 把 Agent Trace 做成可恢复、可回放、可审计的执行记录；这篇讲 Trace 模型、SDK 分层、真实埋点、Trace 调试台，以及 exporter 批量转发和 Collector 幂等收集的设计。',
  content: [
    '这篇接着 Checkpoint 讲，把 nano-notebook 里“怎么知道一个 Agent Run 到底发生了什么”这件事拆开：先定义 Trace 模型，再讲 SDK 为什么值得单独设计，最后落到实际埋点。',
    '我的核心结论是：Agent Trace 不是日志，也不是 OpenTelemetry 的 dashboard。它是一条有身份、有因果、有版本、可以跨进程恢复并且能够回放的执行记录。OpenTelemetry 在 nano-notebook 里只是 best-effort 运维信号；真正用于诊断和复盘的，是应用自己拥有的 Durable Agent Trace。这并不代表没有可视化：nano-notebook 的 Trace 调试台消费的正是这条 Durable Trace 的查询投影。',
    '## 为什么不能只画 Span',
    '普通后端请求的 trace 通常画成一条树：API 进来，数据库、缓存、外部服务作为子 span。它主要回答“哪里慢、哪里错、调用链是什么”。但 Agent Run 比这个复杂：',
    '- 一个 Run 可能排队很久，才被 Worker 真正开始执行。\n- Worker 可能中途崩溃，另一个 Worker 通过 lease reclaim 继续同一个 Run。\n- 同一次模型调用可能因为网络不确定、Provider 超时或进程死亡而变成“不知道是否已经执行”。\n- Action Proposal 可能被接受，也可能只执行了一半。\n- Checkpoint 决定恢复时从哪里继续，但它不回答执行现场发生了什么。\n- Retry 和 delegation 会跨 Run、跨 Attempt，甚至跨 Worker 产生因果。',
    '如果只画 span，会出现一个很常见的误判：看到一个 `started` span 没有对应的 `ended`，就顺手补一个 `error`。但正确语义是“系统只观察到开始，没有观察到完成”，不能把缺失当成失败，也不能把一次没有兑现的执行当成已接受的 checkpoint。',
    '所以 nano-notebook 的 Trace 模型不是“更细的日志”，而是把执行现场建模成可验证的记录流。',
    '## Trace 记录模型',
    'SDK 的底层记录只有四种：',
    '```go\nconst (\n\tRecordSpanStarted RecordKind = "span_started"\n\tRecordSpanEnded   RecordKind = "span_ended"\n\tRecordEvent       RecordKind = "event"\n\tRecordLink        RecordKind = "link"\n)\n```',
    '对应到 Agent 语义：',
    '- Trace：一个 Agent Run 创建一条 Trace，Run admission 时创建 root span。\n- Span：一段有耗时的工作，例如 Attempt、Model Call、Agent Action、Grounding、Publication。\n- Event：一个不可变的瞬时事实，例如 Run admitted、Checkpoint accepted、Lease expired、Run terminal。\n- Link：不改变 parent-child 归属的因果引用，例如 `continues`、`retries`、`retried_from`、`delegates`。',
    '这个模型最重要的设计不是结构，而是身份。Agent Run 会跨进程恢复，所以 span ID 不能只在内存里随机生成；nano-notebook 用 `trace_id + semantic identity key` 派生出确定性的 span ID。Worker 恢复时不需要去查历史 span，只要知道 Run 和 Attempt，就能重建同一个执行上下文。',
    '每条记录还有 schema version、semantic convention version、payload version，并生成 canonical hash。这样 Collector 可以用 `(trace_id, identity_key) + canonical hash` 做幂等接收：同一条记录重发不重复，同 identity 不同内容直接拒绝。历史记录不会因为代码升级就变成不可解释的数据。',
    '## SDK 分层：机制与策略分开',
    '`internal/agentobs` 是一个 Go Agent Observability SDK，但它的边界很明确：SDK 提供记录机制，nano-notebook 提供业务策略。SDK 核心不 import Agent、Job、PostgreSQL、Bifrost 或 HTTP transport，所以未来可以被第二个 Agent 消费，而不是长死在一个 Notebook 产品里。',
    '分层大概是：',
    '```text\nAgent application\n  -> recording API + semantic conventions\n  -> SDK runtime (identity, hierarchy, timing, limits, exporter dispatch)\n  -> instrumentation adapters (Model / Action / Retrieval / Memory / Job)\n  -> exporters (required durable / best-effort OTel / memory test)\n```',
    '应用负责这些策略：什么算一条 Trace，哪些记录是 mandatory，记录失败会不会阻塞业务，哪些字段允许保留，数据跟 Run 删除生命周期怎么走。SDK 不猜这些。',
    '## required 和 best-effort 不能混为一谈',
    '这是整个设计里我认为最值得说的一条：Durable Agent Trace 和 OpenTelemetry 是两个 delivery class，不能互相兜底。',
    '```go\ntype Destination struct {\n\tName     string\n\tClass    DeliveryClass\n\tExporter Exporter\n}\n```',
    '`DeliveryRequired` 的 exporter 失败会返回给应用，调用方不会把一次没有记录的 Model Call 当成已兑现；`DeliveryBestEffort` 的 exporter 失败只进入 bounded diagnostic，不会影响 Agent 正确性。Worker 里同时装了两个 destination：Collector 链路作为 required durable delivery，OpenTelemetry 作为 best-effort telemetry。',
    '这也是 ADR 0029 的边界：OpenTelemetry 可以采样、可以过期、可以只用于运维诊断；Durable Agent Trace 是 Agent 自己的 mandatory history。OTel 成功不能补偿 Durable Trace 失败，OTel 失败也不能否定一个已经持久化的 checkpoint。',
    '## 真实埋点：从 admission 到 terminal',
    '埋点不是到处打日志，而是选择“已经发生的、已经接受的、对恢复有意义的”事实。nano-notebook 实际埋在这些位置：',
    '## Admission',
    '`StartRunTraceInTx` 在 Run 创建事务里创建 root span `agent.execution`，记录 Run、model、prompt version、runtime kind，并写 `nano.run.admitted` event。如果是用户 Retry，新 Run 的 Trace 通过 `retried_from` Link 指回旧 Trace，而不是复用旧 Trace 身份。',
    '## Attempt',
    'Worker 真正 claim Job 时，`StartAttemptTrace` 在 Attempt span 下重建记录上下文。Lease 丢失会写 `nano.lease.expired`，后续 reclaim 通过 `continues` Link 说明“这个 Attempt 继续的是之前那个 Attempt”，而不是凭空出现一个新分支。',
    '## Model Call',
    '`InvokeDecisionModel` 用 instrumentation adapter 包住 `semconv.ModelCall` span，记录 model、phase、decision ordinal、input message count、input hash、prompt identity/version/sha256、finish reason、token、cost。模型调用开始前先写 start record，required 记录失败就直接返回错误，不会开始真正调用。',
    '## Agent Action',
    '`InvokeAgentAction` 包住 `semconv.AgentAction` span，记录 action name、logical id、result status、error kind。Action 重试会通过 `retries` Link 指回上一次尝试；工具因为 availability 或权限被过滤时，写 `nano.tool.filtered` event。检索相关的 Action 还会带 purpose、dense/BM25、rerank、grounding outcome 这些 RAG 语义。',
    '## Checkpoint',
    '`RecordCheckpointAcceptedInTx` 在 checkpoint 接受事务里写 `nano.checkpoint.accepted` event。这是很重要的一点：Trace 记录和业务接受发生在同一个事务边界，所以不会出现“checkpoint 已经接受但 trace 里没有”的假象。',
    '## Publication 和 Terminal',
    '最终发布答案时，先写 `nano.publication` span，在消息和 citation 都落库后写 `nano.publication.passed` event，再通过 `RecordRunTerminalInTx` 写 `nano.run.terminal` event 并结束 root span。这样一条 Trace 从排队到最终答案始终完整。',
    '## 埋点不能把产品事务变成分布式事务',
    '如果每条 Trace 记录都直接写应用 PostgreSQL，Trace 写入失败就可能回滚产品事务。nano-notebook 用 `TraceTransaction` 处理这个矛盾：产品事务打开期间，Trace 记录先写进 transaction-local buffer；事务 rollback 就丢弃，事务 commit 后再 publish 给 exporter。Trace 投递失败会被报告，但不会把已经提交的 Agent 结果改回去。',
    '这也不是无限可靠。当前实现是 bounded in-memory batch exporter：默认 pending 10,000 records / 32 MiB，batch 128 records / 512 KiB，最长 250ms 延迟。进程突然死亡可能丢掉还没发出的记录，Collector 会把这些 Trace 标记为 incomplete，而不是用产品状态补造缺失步骤。',
    'Replay 是另一个边界：模型输入/决策、Action 输入/结果会被应用归一化后再加密成 attachment，只回放这条 Trace 用到的内容；raw provider payload、credentials、hidden reasoning 不会进入 Trace。',
    '## Exporter 怎么批量转发',
    'SDK 的 exporter 不是“每产生一条 span 就发一次 HTTP”。`internal/agentbatch` 里是每进程一个 bounded in-memory batch exporter，默认上限：',
    '- Pending records：10,000\n- Pending bytes：32 MiB\n- Batch records：128\n- Batch bytes：512 KiB\n- Max delay：250 ms\n- HTTP body：2 MiB',
    '`Offer` 先本地校验 envelope，再入队。队列满时丢弃新记录并报告 drop count，保留已有前缀，所以尾部缺失比根被挤掉更可诊断。后台循环按三个条件切 batch：达到记录数、达到字节数、或队首等待超过 max delay；`ForceFlush` 和 shutdown 会强制切当前 batch。',
    '每次 batch 可以包含多条 Trace。`buildBatch` 按 trace 分 chunk，chunk 的 sequence authority 是 `collector`，producer 只给 `(trace_id, identity_key) + canonical sha256`，真正排序交给 Collector。HTTP sender 把 batch JSON gzip 后 POST 到 `/internal/agent-observability/v2/batches`，带 service token。',
    '这里最关键的是重试语义：401/403 永久失败；429、5xx、timeout、不确定 ACK 都会用同一个 BatchID 重发。因为不确定 ACK 时 producer 不知道 Collector 到底提交没有，保守重试比假装成功更安全。Collector 端用身份和 hash 去重，所以重发不会造成重复记录。',
    '## Collector 怎么收集',
    'Collector 的 HTTP handler 限制 body 2 MiB、支持 gzip、验证 Bearer token。`Ingestor.Ingest` 校验 protocol version、producer 是否在 allowlist、schema version 和 sequence authority；一个 batch 里每个 trace chunk 独立返回 `committed / retryable / rejected`，一个坏 chunk 不阻塞其他 trace。',
    'PostgresStore 的 `CommitTraceChunk` 是核心：',
    '- 按 trace_id 拿 advisory lock，避免同一 trace 并发乱序。\n- upsert trace descriptor，读取已 committed prefix。\n- 对每条 record 做 canonical hash 校验。\n- 相同 identity + hash 视为幂等重发；相同 identity + 不同 hash 拒绝为 identity conflict。\n- Collector 给新 record 分配单调 sequence，写不可变 `obs_trace_records`。\n- 所有 record 和 replay payload ref 提交后才 ACK `CommittedThrough`。\n- 只有 committed_sequence 前进时才 enqueue projection，重复 batch 不产生多余投影工作。',
    'raw authority 和查询投影是分开的：',
    '- `obs_traces` / `obs_trace_records` / `obs_payload_refs`：不可变 raw authority，甚至 DB trigger 禁止 update。\n- `obs_trace_summaries` / `obs_spans` / `obs_events` / `obs_links`：从 raw 重建的查询投影。\n- `obs_projection_queue`：projection 工作队列，claim 时 `for update skip locked`，失败按 5s 重试，连续失败 20 次后 abandoned，等新 commit 再唤醒。',
    'Projector 每 100ms 扫一次队列，重建整棵 Trace。`BuildTraceProjection` 根据 record sequence 拼 span tree、event、link，再聚合 token/cost/latency/attempt count。如果 end record 先到而 start record 还没到，projection 会暂时把 terminal 挂起，等 start 到达后重新 projection，不会为了画图而补造一个 span。',
    'Replay 走独立对象存储：producer 先把归一化后的模型输入/决策、action 输入/结果加密到 staging bucket，只有 descriptor 进 batch；Collector 校验 ciphertext size/hash 后搬进自己的 Replay bucket，并写 payload ref。tombstone 优先于后到的 ingestion，删除语义不能因为重发复活。',
    '物理上 Collector 使用独立 Observability PostgreSQL 和独立连接池（ingest/projection/query 分开），Application PostgreSQL 只保留 lightweight trace anchor 和低容量 purge command。Observability 挂了，产品 admission/checkpoint/publication 不阻塞；Trace 最多表现为 incomplete。',
    '## Trace 调试台：让记录变成可调试的工作台',
    '前面这些记录最终都会落到 Collector 的 raw authority 和查询投影。`/admin/traces` 是给 operator 用的 Trace 调试台，它不直接连 PostgreSQL，而是通过 Control Plane 的 `/api/admin/traces` 系列接口读 Collector Query。列表页按 started_at 倒序、cursor 分页，默认 50 条；我们做了多组 filter：可以按 Agent、Model 筛，也可以按任务耗时/时间范围筛，列表行里直接展示 latency，方便从慢任务往下钻。每行还会显示 workload、状态、token、cost；`incomplete` 和 `projection lagged` 是显式状态，不会把“还没观察到完成”显示成正常结束。',
    '详情页把同一条 projection 渲染成几个互补视图：summary header、Trace Tree、Timeline、Inspector。Tree 和 Timeline 是同一份 span/event/link 数据的不同视图；Timeline 会标出未闭合 span，跨 Trace 的 Link 可以直接跳到目标 Trace。Inspector 的 Overview、Attributes、Events & Links 给 span 级事实，RAG Execution 面板从 search_evidence、grounding、publication span 重建 dense/BM25 候选、RRF 顺序、rerank 入选、降级和 publication outcome；Trace Analysis 再把 model call 按 input/output/cached/reasoning token 和 cost 拆开。unknown cost 显示 unknown，不会假装成 0。',
    'Replay 是 Dashboard 里权限最重的一块。前端详情只拿 attachment 引用，不预取 Replay；用户显式点击后才请求 `/api/admin/traces/{trace_id}/replay/{replay_id}`。这个接口单独要求 `platform.trace.replay`，每次允许/拒绝/失败都会写 `platform_replay_access_audit`，响应 `Cache-Control: no-store`。所以敏感 user content 只在该次请求里出现，不会进浏览器缓存、日志或详情页默认加载。',
    '详情页还有一个“只在需要时轮询”的细节：只有当 summary 仍 active，或 `projected_sequence < committed_sequence`（投影还没追上 raw authority）时才每 2 秒刷新；已经 terminal 且投影完整的 Trace 不再轮询。这样实时性只付给真正还在变化的数据。',
    '## 这套模型能回答什么问题',
    '有了 Trace 之后，Agent 的问题终于可以从“这 Agent 不好用”拆成可归因的工程问题：',
    '- Run 慢，慢在 queue wait、model call、tool execution、retrieval 还是 publication。\n- token 贵，贵在 prompt、history、tool schema、tool result 还是反复重试。\n- 失败，失败在模型选择错误、工具结果不可靠、权限被拒、lease reclaim 还是 budget 耗尽。\n- 恢复，能区分“已经完成但没观察到”和“根本没有执行完”。\n- 优化，能把一条线上 trace 沉淀成 eval 样本，而不是每次靠感觉调 prompt。',
    '这正好接上之前写的 Trace -> Eval 思路：Trace 负责归因，Eval 负责验证。没有这种 durable 执行记录，Agent 很容易变成“看起来跑通了，但说不清哪里对、哪里错”。',
    '## 源码锚点',
    '- [internal/agentobs/record.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agentobs/record.go)\n- [internal/agentobs/runtime.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agentobs/runtime.go)\n- [internal/agent/trace_semconv.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/trace_semconv.go)\n- [internal/agent/run_trace_admission.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/run_trace_admission.go)\n- [internal/agent/attempt_trace_recorder.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/attempt_trace_recorder.go)\n- [internal/agent/instrumentation_adapters.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/instrumentation_adapters.go)\n- [internal/agent/checkpoint_trace.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/checkpoint_trace.go)\n- [internal/agent/trace_delivery.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/trace_delivery.go)\n- [internal/agentbatch/exporter.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agentbatch/exporter.go)\n- [internal/agentbatch/http.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agentbatch/http.go)\n- [internal/collector/ingestor.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/collector/ingestor.go)\n- [internal/collector/postgres_store.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/collector/postgres_store.go)\n- [internal/collector/memory_store.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/collector/memory_store.go)\n- [internal/collector/projection.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/collector/projection.go)\n- [internal/collector/projector.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/collector/projector.go)\n- [internal/collector/migrations.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/collector/migrations.go)\n- [docs/technical-architecture/adr/0029-separate-operational-telemetry-from-durable-agent-traces.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/technical-architecture/adr/0029-separate-operational-telemetry-from-durable-agent-traces.md)\n- [docs/superpowers/specs/2026-07-17-go-agent-observability-sdk-design.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/superpowers/specs/2026-07-17-go-agent-observability-sdk-design.md)\n- [docs/superpowers/specs/2026-07-19-direct-trace-delivery-design.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/superpowers/specs/2026-07-19-direct-trace-delivery-design.md)\n- [docs/implementation/sprint-5-agent-trace-operations-runbook.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/implementation/sprint-5-agent-trace-operations-runbook.md)',
    '- [internal/app/admin_traces.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/app/admin_traces.go)\n- [internal/collector/query.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/collector/query.go)\n- [web/src/components/traces/trace-dashboard.tsx](https://github.com/huangxinxinyu/nano-notebook/blob/main/web/src/components/traces/trace-dashboard.tsx)\n- [web/src/components/traces/polling.ts](https://github.com/huangxinxinyu/nano-notebook/blob/main/web/src/components/traces/polling.ts)\n- [web/src/components/traces/types.ts](https://github.com/huangxinxinyu/nano-notebook/blob/main/web/src/components/traces/types.ts)',
  ],
  aiDisclosure:
    '本文由 AI 协助整理表达，技术决策、实现与埋点来自 nano-notebook 仓库源码、设计规范和 runbook。',
  readingMinutes: 11,
  category: 'software',
  topic: 'agent-architecture',
  series: 'nano-notebook-dev-log',
  tags: ['nano-notebook', 'Trace', 'Observability', 'Dashboard', 'Replay', 'OpenTelemetry', 'Collector', 'Agent Runtime', 'Go'],
  status: 'published',
} satisfies BlogPost
