import type { BlogPost } from '../../data/types'

export const nanoNotebookDevLog05 = {
  slug: 'nano-notebook-dev-log-05',
  title: 'nano-notebook 开发日志 05：给知识库装上受控工具：MCP Tool Plane、权限与编排',
  date: '2026-08-07',
  excerpt:
    '从 RAG 到 Agent Runtime：这篇讲 search_evidence 如何变成 MCP 工具，模型为什么只能提议不能直接执行，AgentLoop 如何编排、授权、恢复，以及工具报错、重试、并发结果落库、上下文投影和 Claude Code 机制对比。',
  content: [
    '第四篇讲了 RAG：让模型能在自己的知识库里检索证据。但检索能力不会自动变成 Agent 能力。要让模型真正用上知识库，必须把它包装成一个受控的工具；而工具一旦能被执行，权限、编排和上下文就不再是附加项，它们就是 Agent Runtime 本身。',
    '这篇把 nano-notebook 的工具层、权限、AgentLoop 和上下文处理放在一起讲，正好补上前面几篇留的骨架。',
    '## 先给一个整体画面',
    '我一直用同一个比喻理解 Agent：模型是一个很聪明、但不太可靠的新员工。',
    '- 模型是员工：负责想清楚下一步要什么。\n- 工具是部门：检索、计算、查时间、找外部材料都通过这些部门完成。\n- 权限是门禁卡：员工不能自己开服务器房间，只能进入被授权的区域。\n- 编排是工作流程：想清楚、申请、办事、汇报，然后决定下一步。\n- Runtime 是管理系统：模型只能提交申请，系统负责审批、执行、留痕和恢复。',
    '所以 nano-notebook 的原则不是“把能力都交给模型”，而是给模型一个受控的工作台：**模型提议，系统审批执行，结果受控返回，全程留痕。**',
    '## 工具层：把 RAG 变成一个 MCP Tool',
    'RAG 本身是一条离线索引 + 在线检索链路。模型不能直接拿 Qdrant 或 PostgreSQL，它只能看到一个工具：`search_evidence`。',
    'nano-notebook 的底层 Action 契约非常窄：',
    '```go\ntype Action interface {\n\tDefinition() models.ActionDefinition\n\tValidateInput(json.RawMessage) error\n\tExecute(context.Context, ActionRequest) (ActionResult, error)\n}\n```',
    '每个工具只负责三件事：给出模型可见的定义、校验输入、执行并返回规范化结果。`ActionRegistry` 在启动时校验工具名、描述、输入 schema 和重复注册；重复名字会让进程启动失败，而不是运行时才暴露。',
    '生产路径再包一层 MCP Tool Plane。Worker 启动时把 `calculate`、`current_time`、`search_evidence`、`web_search` 和生成的 `delegate.research.source-discovery.v1` 注册成 `MCPToolRegistration`。每个 Agent Attempt 会打开一个 in-process MCP session，模型通过 `tools/list` 只能看到这个 Agent Definition 允许的工具。',
    '这个设计里最关键的不是“用了 MCP”，而是 Controller 仍然是执行 authority：',
    '- MCP Server 只做 typed adapter，不拥有 Run store、Queue、Retry、权限或产品生命周期。\n- 工具 schema 里只有业务输入，不暴露内部 scope、凭据或 attempt metadata。\n- Host 通过 MCP metadata 注入 attempt-context handle、`action_id`、definition hash 和 tool hash。\n- Server 收到 `tools/call` 后必须解析 handle，重新校验当前 Attempt 的 lease、definition、allowlist、deadline、budget 和产品授权，才能执行。',
    '工具还有调度类型：`ordered_sync`、`parallel`、`exclusive_delegation`。当前 `search_evidence` 是只读的，所以和 `calculate`、`current_time` 一样可以声明为 `parallel`；`web_search` 调用外部限流 Provider，保持 `ordered_sync`；生成的 delegation 工具是 `exclusive_delegation`，只能单独出现在一个 proposal 里，因为调用它会挂起父 Run。',
    '工具是否出现在模型面前也不只由“有没有注册”决定。`search_evidence.Available()` 只在 Run 已选中 Sources 时返回 true；delegation 工具只在成员是 owner/editor、Provider 可用、子 Agent 关系已注册、且没有已存在 child Run 时返回 true。被隐藏的工具会写 `nano.tool.filtered` Trace event，记录工具名和 reason，方便判断“模型为什么没看到它”。',
    '## 权限：模型不能决定自己能用什么',
    '工具层之后，权限就是最不能偷懒的一层。nano-notebook 把它拆成三层：',
    '1. **Definition 是能力上限。** Agent Definition 是 Git-owned、embedded、带版本和 SHA-256 的 JSON。`chat.leader@3` 的 `tools` 只有 `calculate`、`current_time`、`search_evidence`，`children` 只有 `research.source-discovery@1`，limits 是 model_calls 5、actions 8、action_batch 4、context_bytes 65536、result_bytes 65536、attempts 3。\n2. **Executor Registry 是代码级 ceiling。** Definition 可以收窄 Executor 的能力，但不能超出 Executor 注册的能力。启动时 `ValidateBindings` 会拒绝 unknown tool、未绑定 prompt、超限 limit、未注册 child relationship，所以配置不是另一套可执行代码。\n3. **PostgreSQL RLS 是 defense in depth。** 应用请求通过 `set local role nano_app` + `app.principal_id` 在事务内建立 principal；Worker 使用独立 `nano_worker` 角色，并在每次 durable boundary 重新授权。即使应用层查询写错，RLS 也能挡住跨 Notebook、跨用户读取。',
    '对工具调用来说，真正的安全边界是“模型输入不能决定 scope”。`search_evidence` 的输入只有 `query` 和 `purpose`；真正检索哪个 Notebook、哪些 Sources、哪个 Evidence Revision，全部由 Runtime 从 Attempt 和 server-pinned Run Evidence Set 加载。模型想传一个别人的 source_id 也没有这个字段可传。',
    'Delegation 同理：模型只能选择 catalog 生成的 `delegate.research.source-discovery.v1`，不能发明任意子 Agent identity。Controller 接受后，`configuredDelegationAction.schedule()` 会在 PostgreSQL 事务里重新校验 child relationship 和产品 ownership，再创建 durable child Run + Job。权限不是调用时弹一次确认，而是从配置、代码、数据库三层一起 fail closed。',
    '## AgentLoop：模型决策只是循环里的一步',
    '代码里 AgentLoop 就是 `Controller.Execute`。它不是 autonomous loop，也不允许模型无限跑，而是一个有界状态机：',
    '```text\nLoad Execution + CheckpointPrefix\nloop:\n  if 有未完成 Action -> 恢复执行\n  else:\n    构建可用工具列表（availability 过滤）\n    从 durable 状态重建模型上下文\n    CheckAuthority\n    模型返回 Final 或 Action Proposal batch\n    validate proposal（名字、schema、batch limit、exclusive delegation）\n    append Proposal Checkpoint\n    执行 Action\n    append Action Result Checkpoint\nFinal:\n  grounding 校验/规范化\n  append Final Draft Checkpoint\n  Publication Barrier 发布正式消息\n```',
    '每一步都是“模型提议 -> Controller 接受 -> 落 checkpoint -> 执行 -> 落 checkpoint”的闭环。Proposal 本身不产生执行权；只有被验证、被接受、被 checkpoint 的 Action 才会进入 MCP `tools/call`。',
    '模型决策和 Action 都有硬预算。`chat.leader@3` 一个 Run 最多 5 次 model call、8 个 Action、每批最多 4 个 Action；Action Result 有单条和累计字节限制。Action 能力耗尽后，Controller 会保留一个 reserved Final decision，让模型用已接受的结果回答或说明限制，而不是再给更多工具。',
    '恢复也由 Checkpoint 而不是进程状态决定。Append-Only Checkpoint 存 Proposal、Action Result、Final Draft，每个已接受边界有 stable `action_id`。Worker 崩溃后，下一个持有 Lease 的 Worker 从 `firstIncompleteAction` 继续；已接受的 Proposal/Result 不会重复计费。Lease fencing 保证两个 Worker 都认为自己持有同一个 Run 时，只有当前 Lease 持有者能推进。',
    'Delegation 在这个 loop 里也不是特殊分支。它就是模型选择的 MCP 工具：模型 proposal `delegate.research.source-discovery.v1`，Controller 接受后由 runtime 原子创建 child Run + Job，父 Job 进入 waiting，child 完成后父 Run 被 requeue，Controller 从同一个 checkpoint stream 继续。没有单独的路由器替模型决定要不要研究。',
    '## 工具调用报错：先分类，再决定重试还是终止',
    '工具调用错误最怕两件事：把基础设施错误当成业务错误继续跑，或者把业务错误当成系统崩溃直接终止。nano-notebook 用 `ActionResult` 和 `ToolCallError` 把这两类分开。',
    '`ActionResult` 只有两种状态：',
    '```go\nconst (\n\tActionSucceeded   ActionResultStatus = "succeeded"\n\tActionDomainError ActionResultStatus = "domain_error"\n)\n```',
    '`domain_error` 是工具自己声明、有界、可解释给模型的业务错误，比如 `division_by_zero`、`retrieval_unavailable`。它会被当成普通 Action Result 写入 Checkpoint，下一步模型调用时按 tool result 重新进入上下文，让模型决定是换参数、换工具还是直接回答。Runtime 不会因为 domain error 自动重试，因为那是业务决策，不是基础设施故障。',
    '基础设施故障走 `ToolCallError`，并分成四类：',
    '- `authorization`：权限、lease、deadline、attempt authority 丢失。\n- `schema`：工具输入或 MCP 结果不符合契约。\n- `invariant`：definition hash、tool hash、action_id、materialized tool 不一致。\n- `infrastructure`：超时、限流、Provider 不可用、底层调用失败。',
    '`ClassifyAttempt` 再把这些映射成 disposition：`infrastructure` 一般是 `retryable`；`invariant`、`schema` 一般是 `terminal`；lease lost 和 user cancel 是 `abandoned`。error code 只允许 `^[a-z][a-z0-9_]{1,63}$` 这种安全格式，最终写进 `agent_jobs.last_error_code` 和 `agent_runs.error_code`。Provider 的原始报错 body 不进入模型上下文，也不进入 Run 权威状态。',
    '## 并发工具结果怎么落库',
    '一个 Proposal 最多可以有 4 个 Action。如果 batch 里所有 pending Action 都声明为 `ToolParallel`，Controller 会走 `executeParallelBatch`：先串行 preflight（解析 executor、构造请求、查 retry span），再并发执行，最后按原 Action index 顺序返回结果。',
    '并发结果落库的关键是：**允许 Action Result 乱序落库，但不允许重复或覆盖。**',
    '`CheckpointPrefix` 允许同一个 Proposal 里的 Action Result 以任意 index 顺序出现：先完成的 Action 可以先 append。但每个 `action_id` 只能有一个 Result，相同 identity + 相同 payload 是幂等重放，相同 identity + 不同 payload 是 checkpoint conflict。模型上下文重建时仍然按 proposal 里的 index 顺序生成 tool call/tool result，所以无论并发完成顺序是什么，模型看到的顺序是确定的。',
    '如果并行 batch 里某个 Action 失败，成功的 siblings 仍然会 commit；失败的那一个 index 留在“未完成”集合里，交给 Attempt retry 路径恢复。字节预算按 index 顺序累计，超预算的部分不会继续 commit，避免“虽然没超单条限制，但整批结果把上下文预算打爆”的假象。',
    '## 重试：Attempt 级与 Action 级',
    'nano-notebook 有两条重试语义，别混在一起。',
    '**Attempt 级重试**处理基础设施故障。Worker 得到 `AttemptRetryable` 后，Job Queue 会把 Job 重新放回 `queued`，用 `AttemptRetryBackoff` 计算 1s、2s、4s 这种 bounded exponential backoff + deterministic jitter，上限 30s；同时检查 Attempt 次数和 Run deadline。`chat.leader@3` 默认 attempts 3，超过后变成 `retry_exhausted`，deadline 已过则变成 `run_deadline_exceeded`。每次 retry 都会写 `nano.attempt.disposition` Trace event，包含 error_code 和 backoff。',
    '**Action 级恢复**处理“已经执行但还没落库”的不确定状态。外部调用只承诺 bounded at-least-once，所以进程崩溃后，同一个 `action_id` 可能被重新执行。只读工具天然容忍重复；delegation 通过 `action_id` 在 `agent_run_delegations` 上做数据库幂等，不会重复创建 child Run。已接受的 Action Result 直接跳过，不重复计费。',
    '两条语义合起来的效果是：domain error 由模型决定下一步；infrastructure error 由 Runtime 重试整个 Attempt；已完成的 Action 结果永远不丢；未完成的那一个 Action 从 checkpoint 恢复继续。',
    '## 上下文：每次模型调用都从 durable 状态重建',
    'nano-notebook 没有“进程内 conversation”这个权威。每次模型调用前，`BuildDecisionRequest` 都从 Chat + Accepted Checkpoints 重新拼上下文。',
    'Source-less 的 bare 路径读取最近 20 条 durable Chat Message。Source-selected 的 grounded 路径更严格：当前 Message 是 authority，最近已完成对话只作为 reference-only 来消解代词和省略，最多 3 个 pair，总预算 4000 runes，单条 message 1200 runes，当前 Message 最多 4000 runes。',
    '这是有意做的取舍。第四篇之前我们遇到过小模型被旧答案锚定的问题：用户换了个话题，模型却继续用上一轮 search query。所以 grounded prompt 明确写“current message authoritative，recent context reference-only”，query 必须保留当前 Message 的关键词、实体、单位和语言，不能用旧话题替代新话题。这是 prompt 层约束，不再单独跑一个强制 first-search 的上下文隔离模型。',
    '工具调用也一样可重建。Controller 接受 Proposal 后，`BuildDecisionRequest` 会把已接受 checkpoint 恢复成 provider-neutral 的 assistant tool-call 消息和 action-result 消息，再发给模型。稳定 `action_id` 是跨恢复、跨 retry 的 identity，Provider 自己的 call ID 不进入 Agent 权威状态。',
    '检索结果还有专门的上下文投影：`search_evidence` 的原始 Action Result 不会整包塞进模型。Runtime 会从 server-pinned scope 重新加载 evidence candidates，再把模型可见输出压到 8KB 预算。模型拿到的是证据 manifest/有限 preview，不是原始 Qdrant 返回或整段 Source。',
    '上下文不是“能塞多少塞多少”，而是每个 Agent Definition 都有 `context_bytes` / `result_bytes` 预算，Agent Tree 会累计扣减；超限 fail closed，而不是悄悄截断关键状态。工具定义也受 budget 约束，可用工具先被 availability 过滤，避免模型在没必要的工具 schema 上浪费上下文。',
    '## 上下文太长怎么办',
    '当前 nano-notebook 的策略不是“等到超限再压缩”，而是在写上下文之前就做三层有界化：',
    '1. **窗口有界。** bare 路径最多 20 条 durable message；grounded 路径只给当前 Message 加最多 3 组 reference-only 历史。\n2. **单条有界。** grounded 的当前 Message 最多 4000 runes，历史 message 最多 1200 runes；`truncateRunes` 按 Unicode code point 截断，不会切断 UTF-8。\n3. **结果投影有界。** `search_evidence` 不把原始结果塞进上下文，而是先落一个 compact manifest，再在每次模型调用前重新加载 evidence 并投影到 8KB。超过预算就丢候选、截断 top preview，并显式标 `truncated` / `omitted_count` / `preview_truncated`。',
    '所以现在没有做 LLM compaction。Checkpoint、Chat、Evidence 都是权威状态，如果为了省 token 把它们替换成一段模型生成的摘要，等于在恢复链路上引入第二个 authority，Replay 和 Citation 都会失去可验证性。以后如果做长会话，更合理的边界是：只压缩非 grounding 的聊天历史，不压缩 accepted search evidence / citations；overflow 时最多 compact + retry 一次，不能循环压缩。',
    '## Claude Code 的上下文机制，哪些适合 nano',
    'Claude Code 代表的 coding agent 上下文工程，给我们的参考不是“照抄”，而是一份机制清单：',
    '- **Tool search**：模型先只看到搜索工具，需要时再加载 3 到 5 个相关工具，避免所有 tool definitions 常驻上下文。Anthropic 文档举例一个多 server 的典型配置工具定义可能到 55k tokens。\n- **Programmatic tool calling**：Host 不只把工具列表交给模型，还能按程序逻辑选择、并行或组合工具调用。\n- **Prompt caching**：对稳定的 system prompt、tool definitions 和常驻指令做缓存，减少重复计费。\n- **Compaction**：上下文接近阈值时，把旧对话总结成摘要，后续从摘要继续，而不是一直 append。\n- **Context editing**：清理旧 tool result、思考块或中间过程，让模型只看当前真正需要的信息。',
    '哪些适合 nano？',
    '- **Tool search** 适合工具目录变大之后做，但现在不急着做。nano 的工具只有几个，而且 MCP session 已经按 Agent Definition 和 `Available()` 做了两层过滤；工具多了以后，Tool search 应该加在 MCP Host/Tool Registry 层，而不是让模型在 prompt 里选。\n- **Programmatic tool calling** 和 nano 的方向一致，但 nano 已经把它做成了更严格的形态：Controller 拥有 scheduling 和 execution authority，模型只 proposal，不直接调用 Provider SDK。\n- **Prompt caching** 是以后值得做的成本优化。nano 每次从 durable 状态重建请求，stable system prompt 和 tool definitions 很适合做显式 cache key；但要小心 prompt version、definition hash、tool hash 变化必须让 cache 失效。\n- **Compaction** 不能直接照抄到 grounded 答案。nano 用 checkpoint + projection 避免了无界上下文；真要长会话时，只压缩非 grounding 聊天历史，并且不能把 accepted evidence 换成摘要。\n- **Context editing** 在 nano 里更适合做成“投影层编辑”，而不是修改 durable checkpoint。Checkpoint 保持 append-only，模型看到什么可以在 `BuildDecisionRequest` 的 projection 里控制。',
    '## 骨架到这里就逐步填充完了',
    'RAG 给了模型知识库；工具层让知识库变成可调用的能力；权限让能力只能按边界使用；AgentLoop 让“检索 -> 判断 -> 再检索 -> 回答”成为可恢复的循环；上下文处理让每次循环都能从 durable 状态重放。前面几篇的 Runtime 骨架，到这里开始被真实能力填满。',
    '## 源码锚点',
    '- [internal/agent/controller.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/controller.go)\n- [internal/agent/mcp_tool_plane.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/mcp_tool_plane.go)\n- [internal/agent/actions.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/actions.go)\n- [internal/agent/attempt_disposition.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/attempt_disposition.go)\n- [internal/agent/executor_registry.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/executor_registry.go)\n- [internal/agent/configured_delegation_action.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/configured_delegation_action.go)\n- [internal/agent/checkpoint.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/checkpoint.go)\n- [internal/agent/checkpoint_prefix.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/checkpoint_prefix.go)\n- [internal/agent/context_builder.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/context_builder.go)\n- [internal/agent/query_contextualization.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/query_contextualization.go)\n- [internal/agent/search_evidence_projection.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/search_evidence_projection.go)\n- [internal/agent/search_evidence_contract.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/search_evidence_contract.go)\n- [internal/agent/postgres_runtime.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agent/postgres_runtime.go)\n- [internal/jobs/queue.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/jobs/queue.go)\n- [internal/worker/service.go](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/worker/service.go)\n- [internal/agentcatalog/definitions/chat.leader.v3.json](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/agentcatalog/definitions/chat.leader.v3.json)\n- [internal/promptcatalog/prompts/agent.chat-composer-grounded.v3.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/internal/promptcatalog/prompts/agent.chat-composer-grounded.v3.md)\n- [docs/technical-architecture/adr/0014-enforce-authorization-in-go-and-postgresql-rls.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/technical-architecture/adr/0014-enforce-authorization-in-go-and-postgresql-rls.md)\n- [docs/technical-architecture/adr/0030-cancel-cooperatively-and-publish-through-a-barrier.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/technical-architecture/adr/0030-cancel-cooperatively-and-publish-through-a-barrier.md)\n- [docs/technical-architecture/adr/0044-use-mcp-as-the-agent-tool-plane.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/technical-architecture/adr/0044-use-mcp-as-the-agent-tool-plane.md)\n- [docs/technical-architecture/adr/0045-migrate-all-agents-to-an-embedded-definition-catalog.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/technical-architecture/adr/0045-migrate-all-agents-to-an-embedded-definition-catalog.md)\n- [docs/technical-architecture/adr/0047-delegation-is-a-model-chosen-mcp-tool.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/technical-architecture/adr/0047-delegation-is-a-model-chosen-mcp-tool.md)\n- [docs/superpowers/specs/2026-08-04-prompt-driven-leader-decision-loop-design.md](https://github.com/huangxinxinyu/nano-notebook/blob/main/docs/superpowers/specs/2026-08-04-prompt-driven-leader-decision-loop-design.md)',
    '## 参考资料',
    '- Anthropic Manage Tool Context：https://platform.claude.com/docs/en/agents-and-tools/tool-use/manage-tool-context\n- Anthropic Tool Search Tool：https://platform.claude.com/docs/en/agents-and-tools/tool-use/tool-search-tool\n- Anthropic Compaction：https://platform.claude.com/docs/en/build-with-claude/compaction\n- Anthropic Context Editing：https://platform.claude.com/docs/en/build-with-claude/context-editing\n- Anthropic Prompt Caching：https://platform.claude.com/docs/en/build-with-claude/prompt-caching',
  ],
  aiDisclosure:
    '本文由 AI 协助整理表达，技术决策、实现与埋点来自 nano-notebook 仓库源码、ADR、prompt catalog 和设计文档。',
  readingMinutes: 12,
  category: 'software',
  topic: 'agent-architecture',
  series: 'nano-notebook-dev-log',
  tags: ['nano-notebook', 'Agent Runtime', 'MCP', 'Tool', '权限', '编排', '上下文', 'Go'],
  status: 'published',
} satisfies BlogPost
